### ISSUE TITLE
FR: Unique file names

### ISSUE THREAD

**Issue by Athrunen** [kevboh/longform#101]
When writing articles through longform, especially in a big vault, creating scenes with the same name as a file somewhere in the vault is bound to happen.

This is problematic for at least two reasons:

1. Clutter in search results that are hard to differentiate between
2. Scenes taking the place of legitimate wikilinks

The second one is especially bad for the poor souls that have "automatically update internal links" turned on and then go rename a scene with an unintended link pointing at it.

One solution for this would be a prefix, either generated from the project title or chosen by the user, that gets added to every scene and is removed again during compile or when displayed in the side panel.

**Comment by kevboh** [comment]
I'm not sure this is a problem unique to Longform: for example, someone who uses folders and has a large vault could just as easily run into this issue with no plugins installed.

As such, I'm hesitant to add this as a feature. Ideally this would exist as a separate plugin that can live alongside other plugins, and you just happen to add your Longform project folders to this theoretical plugin's prefixing scheme. Going to close this for now.

**Comment by Athrunen** [comment]
Then could the longform ui give an indication that a file with the same name already exists in the vault, so as not to accidentally shadow an existing file or link? Because the obsidian quick switcher will do that for you.

About that whole prefix plugin thing, the amount of work that needs to be done to properly support longform would be rather complex and specific. For example, you would at least need steps to remove the prefix and some kind of rewrite filters to remove it from the side panel to not have the prefix clutter up the scene list. And you would have to make sure to set the correct name for the file as well as the scene list, which requires either some kind of function call manipulation specifically for the longform plugin or automatically changing the correct scene name in the correct index file. Which requires up-to-date and accurate knowledge of internal longform code and/or structuring.

That's why I think a native implementation for this is warranted.

Also, considering the fact that longform will generate a lot of small files and given the use of drafts a lot of duplicate names too, it will probably be one of the plugins that by its very design generates a lot of clutter. So some way to keep that clean might be useful. But that would probably go even beyond some unique names.

**Comment by kevboh** [comment]
That all makes sense—the shadowing warning is easy, I'll file that as an additional ticket: https://github.com/kevboh/longform/issues/102

I'll keep this closed but think about the rest. It's a good idea, I just worry about it being sort of a rabbit hole for a very particular use case.
