### ISSUE TITLE
[UX bug] A + button not fully fit to the 1.0 Obsidian in beta

### ISSUE THREAD

**Issue by danieltomasz** [kevboh/longform#106]
Thanks for updating the plugin, I still see that something  still can  be done with this "+" add button to allign the character with the button
<img width="319" alt="image" src="https://user-images.githubusercontent.com/7980381/195948378-6f7c245d-3c4a-4530-a05b-ab40487f40fb.png">

**Comment by danieltomasz** [comment]
Also in the Minimal theme the "Longform" is doubled when text labels for primary naviagation is enabled
![image](https://user-images.githubusercontent.com/7980381/197070615-2565b4eb-55c2-47f9-9dac-1f5b91ad52d8.png)

**Comment by kevboh** [comment]
Minimal issue fixed in [453f4e7](https://github.com/kevboh/longform/commit/453f4e752980e1067b31515d5377e93779ec332d)

**Comment by kevboh** [comment]
This is fixed in the the current beta. Remove and reinstall from BRAT.

**Comment by danieltomasz** [comment]
Thanks for the fast fixing!
