### ISSUE TITLE
Big margins when click

### ISSUE THREAD

**Issue by dipsy** [kevboh/longform#107]
<img width="324" alt="Снимок экрана 2022-10-16 в 15 06 49" src="https://user-images.githubusercontent.com/1336665/196058398-4832a56a-e444-4d07-bf22-2dd1a5679394.png">
<img width="322" alt="Снимок экрана 2022-10-16 в 15 09 13" src="https://user-images.githubusercontent.com/1336665/196058451-539ed60b-089f-4611-a7ed-55838eee1a4d.png">

Bacause that, cant click to arrow to navigate scenes
Also in all others places such problem, but nested scenes became fully unusable

Obsidian 1
Plugin latest

**Comment by dipsy** [comment]
my theme is Default ..

**Comment by kevboh** [comment]
It looks like you're using an old version of the beta, based on that screenshot. Can you update (remove and re-add to BRAT) and try again? I don't fully follow what the problem is, also.

**Comment by dipsy** [comment]
i find the problem plugin: https://github.com/search?q=cMenu+obsidian
It brings class .sortable-chosen to the li tag
disable it and all ok
