### ISSUE TITLE
Unsuccessful migration from version 1 to 2

### ISSUE THREAD

**Issue by larsenkg** [kevboh/longform#112]
I upgraded the plugin to version 2.0.0 and clicked the Migrate button. I didn't receive an error, but the Longform pane is empty, as shown below:

![image](https://user-images.githubusercontent.com/28319797/198854276-34dddc17-d8c3-44cf-95cf-a9891d7fb2c1.png)

Upon restarting Obsidian, the Migrate button is back. Clicking it again has the same effect. 

The vault/project contained a brand new story that only had one draft and one scene (so far).

My post-migration Index.md file is as follows:

``` 
---
version: 1
workflow: null
drafts:
  - name: Draft 1
    folder: Draft 1
    scenes:
      - Jash runs through the forest
---


This file is managed by Longform. Please avoid editing it directly; doing so will almost certainly confuse the plugin, and may cause a loss of data.

Longform uses this file to organize your folders and notes into a project. For more details, please see [The Index File](https://github.com/kevboh/longform#the-index-file) section of the plugin’s README.



This is a Longform 1.0 Index File, and the project it corresponded to has since been migrated. It has been marked as to-be-ignored in the new project and can be safely deleted.

This is a Longform 1.0 Index File, and the project it corresponded to has since been migrated. It has been marked as to-be-ignored in the new project and can be safely deleted.

This is a Longform 1.0 Index File, and the project it corresponded to has since been migrated. It has been marked as to-be-ignored in the new project and can be safely deleted.
```

Here is the post-migration plugin data.json file:

```
{
  "version": 2,
  "projects": {
    "Book 1": {
      "path": "Book 1",
      "indexFile": "Index",
      "draftsPath": "Drafts/"
    }
  },
  "selectedDraftVaultPath": null,
  "userScriptFolder": null,
  "sessionStorage": "plugin-folder",
  "sessions": [],
  "showWordCountInStatusBar": true,
  "startNewSessionEachDay": true,
  "sessionGoal": 2500,
  "applyGoalTo": "all",
  "notifyOnGoal": true,
  "countDeletionsForGoal": false,
  "keepSessionCount": 365,
  "sessionFile": "longform-sessions.json",
  "numberScenes": false,
  "workflows": {
    "Default Workflow": {
      "name": "Default Workflow",
      "description": "A starter workflow. Feel free to edit, rename, or delete it and create your own.",
      "steps": [
        {
          "id": "strip-frontmatter",
          "optionValues": {}
        },
        {
          "id": "remove-links",
          "optionValues": {
            "remove-wikilinks": true,
            "remove-external-links": true
          }
        },
        {
          "id": "prepend-title",
          "optionValues": {
            "format": "## $1",
            "separator": "\n\n"
          }
        },
        {
          "id": "concatenate-text",
          "optionValues": {
            "separator": "\\n\\n---\\n\\n"
          }
        },
        {
          "id": "write-to-note",
          "optionValues": {
            "target": "manuscript.md",
            "open-after": true
          }
        }
      ]
    }
  }
}
```

I then tried to migrate manually. I moved my scene to a "Scenes" folder and created a draft index file called "Draft 1.md" with the following contents:

```
---
longform:
  title: Book 1
  format: scenes
  sceneFolder: Scenes
  scenes:
	- Jash runs through the forest
  ignoredFiles:
    - Index
---
```

I updated the plugin data.json file to set the `version` to 3 and the `projects` to {}. After restarting Obsidian, the Migrate button disappeared, but the Longform pane still appears the same as in the image above. 

I was able to get Longform to work after re-installing it. A couple things that are different now:
 - `selectedDraftVaultPath` is no longer null
 - The draft index is inside my Scenes directory instead of in the Longform project root directory (`/Book 1/Scenes/Index.md`)
 - The draft index title now matches the scene directory ("Scenes")

Let me know if you need any more information to help smooth out the migration procedure.

**Comment by kevboh** [comment]
This is helpful. I'd have to try and recreate this to see what happened.

The results of your manual migration make sense. Index files live at the draft level now, and default to the name of their enclosing folder if no explicit name is specified.

**Comment by PeteMichaud** [comment]
@larsenkg Can you tell me what the `selectedDraftVaultPath` variable was set to after you reinstalled? I tried these steps, but it's still null and not working.

**Comment by kevboh** [comment]
See also #116, trying to nail this down. @PeteMichaud if you're still seeing this, what happens if you:

1. Close Obsidian
2. Manually set `selectedDraftVaultPath` to a project's index file's path relative to vault root. For example, for a project in `some-folder/` with an index file named `my-project.md`, it would be `some-folder/my-project.md`.
3. Reopen Obsidian

**Comment by kevboh** [comment]
Just to drop a note here—try clicking the blank space where the project name should be. This will be fixed in the next release.

**Comment by kevboh** [comment]
2.0.2 should fix this. Please let me know if it does not.
