### ISSUE TITLE
Cannot click any item in scences.

### ISSUE THREAD

**Issue by q7z** [kevboh/longform#118]
So every time I click on an item from a project in the scenes, the item isn't opened in a pane. Cmd+click doesn't do anything either. Instead, it seems to just "pull" the file, as though I am trying to reorder the scene(cursor changes to the pan/hand cursor).
I am using the Anpucin theme. I tried this while turning off the themes, as well as reinstalling longform and resetting all my projects. Don't know how to solve this :(

**Comment by musicleaf** [comment]
我也遇到这个问题

**Comment by kevboh** [comment]
What's your operating system and version, and what version of Obsidian are you using?

**Comment by musicleaf** [comment]
MAC  ，
<img width="228" alt="image" src="https://user-images.githubusercontent.com/35360006/204295661-e509eac2-3678-49d2-953e-95d34d0080b8.png">
<img width="260" alt="image" src="https://user-images.githubusercontent.com/35360006/204295726-33da815c-251e-4066-b976-10987b18982b.png">

**Comment by wnhllh** [comment]
same problem

**Comment by musicleaf** [comment]
用了cmenu（包括editing toolbar）就会出现这样的状况, 停止使用这两个插件就解决了。 插件出现冲突

**Comment by q7z** [comment]
> What's your operating system and version, and what version of Obsidian are you using?

I have this issue across my MacOS Monterrey and Windows 10 PC, Running the latest Obsidian 1.1.14

**Comment by cumany** [comment]
This problem caused by editing toolbar has been fixed.
 https://github.com/cumany/obsidian-editing-toolbar/releases/tag/2.2.3

**Comment by q7z** [comment]
> This problem caused by editing toolbar has been fixed. https://github.com/cumany/obsidian-editing-toolbar/releases/tag/2.2.3

I don't even have this plugin, is there maybe another one that might be conflicting with longform?

**Comment by Drakemoor** [comment]
> I don't even have this plugin, is there maybe another one that might be conflicting with longform?

cMenu plugin does the same. turn it off and problem is fixed.
