### ISSUE TITLE
Bug: "Mark as Longform Project" doesn't exist

### ISSUE THREAD

**Issue by namtrah** [kevboh/longform#127]
For whatever reason, I had been working on a longform project and after an obsidian reboot the plugin no longer saw that it was one. I right clicked on the folder to "Mark as Longform Project" as it says in the description, but I cannot find that option. Only "Create a new Longform Project" which fails because it finds the index.md and complains that one exists already. 

I have looked for any command called "Mark as Longform project" and cannot find any. Was this removed in the latest release? I am using version 2.0

**Comment by kevboh** [comment]
> Was this removed in the latest release?

Yes, it was removed in 2.0. There is [documentation](https://github.com/kevboh/longform/blob/main/docs/MIGRATING_FROM_VERSION_1_TO_2.md) available on the migration. Essentially, Longform projects are now discovered automatically by the presence of the index file—you no longer mark or unmark folders as such. The relative location of the index file has also moved: what was a draft in Longform 1.0 is now a project, allowing finer-grained composition and more flexible setups.

Closing this, but happy to answer more questions here if you have any.

**Comment by namtrah** [comment]
Thank you for the explanation. I guess I found the bug. It seems that when I had a set of projects that the Longform couldn't read. There were several errors in Obsidian which I couldn't work around until I did several things.

One is that I had Links in my Scenes (by accident). 
`````
scenes:
  - [[link]]

This totally killed the longform automatic processing, but there wasn't any sort of "useful" or directive error message. I know I shouldn't touch the file, but in migrating, it is way to easy to copy/paste stuff from an old to a new one. Can that be at least documented as a "do not do" issue?

Secondly, I also just went into the data.json and had to rip out old, unshed (and most likely wrongly migrated) projects until it worked again.

I am back up and running, but I thought you might like to know of the edge cases for your auto-discovery of a project or list of projects.
