### ISSUE TITLE
Bug: move a scene from one draft to another causes issues

### ISSUE THREAD

**Issue by pdworkman** [kevboh/longform#129]
Right now, moving a scene from one draft to another causes some weird issues. There doesn't seem to be a way to do it cleanly.

**Comment by kevboh** [comment]
Can you elaborate? What issues? This should just work.

**Comment by pdworkman** [comment]
Here is what happened for me:

I realized that "document A" that was in "Draft 0" should have been in "Draft 2". I used the Obsidian move command to move it from "Draft 0" to "Draft 2". It moved the original "document A" into "Draft 2". However, Longform also created a blank "document A" in "Draft 0".
