### ISSUE TITLE
Feature Suggestion: Compile option to regex-replace / remove tags / etc.

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#13]
I think a compile option for those would be helpful. Stuff like tags can be helpful during writing, but are often unnecessary for the finished work. in a more abstract sense, some replace / regex functionality during compile might be useful.

Such a feature could also be used to implement sth like variables for a longform project – you would define variables in a separate note and during compile you would insert the variables there. Something like this could be useful for character names etc. [This pandoc filter](https://github.com/michaelstepner/pandoc-mustache) does something quite similar by by using "mustaches" (`{{variable}}`) to mark variables.

**Comment by kevboh** [comment]
This is definitely planned. My current goal is to provide a slate of compile steps that allow some customization, plus steps that are user scripts for full flexibility. Closing as this is part of #2—I'll copy the relevant bits there.
