### ISSUE TITLE
Feature request: reveal project in file explorer

### ISSUE THREAD

**Issue by pdworkman** [kevboh/longform#130]
The previous version of Longform had a feature to reset all projects and start over. This was helpful if something got corrupted and wasn't working the way that it should. In the current version, there doesn't appear to be a way to reset all projects (and if you have accidentally defined a sub-sub-folder as a project my mistake, it can be difficult to find it, especially if you use standard folder naming conventions between projects. (Which "draft 1" in this 21 book series was accidentally set as a project?)

**Comment by kevboh** [comment]
I think the solution to your specific problem here is adding a right-click menu option or a command to show a Longform project's folder in the Obsidian file explorer. The reason the reset button was removed is that to reset Longform 2.0 would mean mass-deleting all projects—metadata is continually inferred by the contents of the vault, which is the source of truth.

**Comment by kevboh** [comment]
Okay if I rename this issue to reflect my suggestion of a reveal command?

**Comment by pdworkman** [comment]
I think that would be helpful. 

Rename away.

**Comment by kevboh** [comment]
This will be added in the next release.
