### ISSUE TITLE
Display Bug

### ISSUE THREAD

**Issue by pdworkman** [kevboh/longform#132]
I reinstalled Longform in a vault that it had previously been installed in. 

A console note came up that it had found 7 drafts to watch. 

On the Longform panel, however, there were no projects or drafts visible. 

I clicked the blank space on the panel where the projects should have been listed, and two projects appeared in the drop-down list as they should. (One with two drafts and one with five.) This appears just to be a screen draw issue.

**Comment by kevboh** [comment]
Yeah, initial migration can leave that picker in a weird state. Thanks for filing, I'll leave this open as it's nice and specific.
