### ISSUE TITLE
Feature Request: new file template

### ISSUE THREAD

**Issue by pdworkman** [kevboh/longform#134]
Each new scene I create, I add my YAML form to be filled in. It would be nice if there was a place in settings where I could specify a new scene template that was automatically used for each new file.

Yes, I can use Obsidian templates to do this. Currently I have it set up as a TextExpander snippet, and either way it is only a few keystrokes to insert it. Just a "nice to have" feature.

**Comment by kevboh** [comment]
Makes sense. Should maybe be a per-project setting? Thanks for filing.

**Comment by pdworkman** [comment]
Yes, for me it would be per project.

**Comment by kevboh** [comment]
This will be available in the next release. There is a project-wide setting in the plugin settings, plus per-project settings in the Project Metadata section of each project.
