### ISSUE TITLE
Appearance: Collapsing headings with Minimal Theme

### ISSUE THREAD

**Issue by mac-obs** [kevboh/longform#138]
**Versions**
Longform version: 2.0.3
Obsidian version: v1.1.9
OS Windows 
Theme: Minimal

Collapsing the headings in Longform Pane does not move the collapsed top level headings next to each other but just hides the subheadings. This seems to be connected to the Minimal Theme: Collapsing works just as expected if I use the default theme. 

![Example](https://user-images.githubusercontent.com/111188217/211365973-34d0e2f4-37a5-453a-97b9-bf0d38be9cb8.png)

**Comment by kevboh** [comment]
I can take a look, but it is exceedingly difficult to debug against themes, and this might end up being a situation where a CSS snippet is your best bet.
