### ISSUE TITLE
This does not work as described when installed on the iPad pro

### ISSUE THREAD

**Issue by Nunnyafbdjdj** [kevboh/longform#139]
“You should see three tabs: Scenes, Project, and Compile” This does not happen. And there is nowhere on the internet that offers and explanation or any kind of troubleshooting. I will sign up for your little sponsorship thingy or whatever GitHub calls it if anyone can just help me. Even just a response to this message would let me know I am alive.

**Comment by kevboh** [comment]
You're alive. Hope this helps.

I'll check out things on iPad. Screenshots or an anonymized vault would help. You don't need to give me money unless you genuinely want to.

**Comment by Nunnyafbdjdj** [comment]
Just hearing back from someone, I can’t explain. I’ll send anything, screenshots, vaults, anything, just anything to let me know that this is even solvable or what is supposed to happen or whatever. But I don’t know how to send anything like a vault thingy. 
![76118A13-B815-4A07-99B4-C3DD8E16D1AF](https://user-images.githubusercontent.com/123130962/213595505-fd353f86-80d1-4f17-81bb-90805941cbe4.png)
![C599CC6E-5ED1-4897-9C87-9CC0F27DCF18](https://user-images.githubusercontent.com/123130962/213595508-990bce67-51be-404f-93b0-411eea51f912.png)
![3619219C-93B3-4FD0-B175-5E549F3D148C](https://user-images.githubusercontent.com/123130962/213595510-02e3eb81-3f68-4135-bbcf-46e07c50cc1f.png)
Or if you can tell me how to share a “vault”?

**Comment by Nunnyafbdjdj** [comment]
I am don’t know what to show in a screenshot
![EADABB6F-A486-4E98-B828-CB0EF34293DE](https://user-images.githubusercontent.com/123130962/213595626-8bc6b201-3828-44dc-8a43-7fb5dc555a14.png)

**Comment by Nunnyafbdjdj** [comment]
I’ll give you money, I can only afford the $5 tier but I have wanted to give that money just to know I’m not going crazy. Cause to be honest the past few days trying to figure things out.

**Comment by Nunnyafbdjdj** [comment]
Also, what is the Longform: Start New Writing Session command? I don’t understand what this is or where to find it. I’ve clicked and right-clicked on every button in the Obsidian interface and besides the plug-in settings and the little keyboard shortcut assigner thingy, nowhere does it say “Start New Writing Session command”

**Comment by kevboh** [comment]
Okay, first take a deep breath. This is just software. And it's _open source_ software, which means it's not my day job and is 100% not worth driving yourself crazy over. I have a job, a family, and lots of life obligations; I also, to reiterate what I said above, do not need you to sponsor me.

What is in the file named `Index` in your first screenshot? Based on what you have here it looks like you don't have any projects; you'll need to create one. You can do so in a few ways. My iPad is out of battery at the moment, so I can't test exactly which ways will work for you, but one that definitely will would be to:

1. Create a folder for your project
2. Create a note inside that folder
3. In that note, run the Insert multi-scene frontmatter command

At that point you should have a project in the Longform pane.

`Start New Writing Session` resets words counts for a project. It will do nothing until you create a project and start writing in it. It's not a command you will likely use often.

**Comment by Nunnyafbdjdj** [comment]
I have to go home from work now. I will look at your suggestions when I arrive at my home.

**Comment by Nunnyafbdjdj** [comment]
Tomorrow I will try to sit down with it. I will try your suggestions. I haven’t been able to go through your response, but I am relieved that there is someone who understands it

**Comment by colintedford** [comment]
To find "Longform: Start New Writing Session command", open the [Command Palette](https://help.obsidian.md/Plugins/Command+palette) and type "start". The Command Palette's icon is in the Ribbon (the strip of icons in the left of the left sidebar); it looks like `>_` in the default theme.

**Comment by Nunnyafbdjdj** [comment]
I tried the instructions in your post. I can’t tell but it looks like nothing happened. I also right click on the folder and choose “Create Longform Project” and nothing happens. 

https://user-images.githubusercontent.com/123130962/213847248-e31a3348-51cf-4204-9c12-3235c88f5f31.MOV

**Comment by Nunnyafbdjdj** [comment]
I’d love to see this as seen is the GitHub description. I’m just not sure how to make it work.
![3FCD2F2B-031A-433A-BB53-46609B37C964](https://user-images.githubusercontent.com/123130962/213847330-d7583841-800c-4e0d-b099-b769ca7f45c0.jpeg)

**Comment by Nunnyafbdjdj** [comment]
Here is a way I tried again.

https://user-images.githubusercontent.com/123130962/213847416-94e3d6d8-6ba4-419e-a954-4bd0103f32c8.MOV

**Comment by kevboh** [comment]
Yeah, based on your video it looks like running the command is broken on iPad. I'll try it on mine shortly. If you'd like you can also just write the frontmatter manually in the meantime. Put this into your note:

```
---
longform:
  format: scenes
  sceneFolder: /
  scenes: []
---
```

Note the spacing above—you can copy/paste that directly if you'd like.

**Comment by kevboh** [comment]
Okay, I tested this on my iPad Pro and it's also working there. Could you try something for me?

1. Create the note as in the instructions.
2. **Place the cursor in the editor for the note**
3. Run the "Insert multi-scene frontmatter" command

Step 3 might be easier for you if you have a keyboard attached and use the cmd-P shortcut, but either way should work—I tested both. I noticed in your video that you tap outside the editor prior to running the command, which may contribute to it not working. It's a bug either way, but this might unblock you.

**Comment by kevboh** [comment]
I also tested the folder -> Create Longform project option, which also works for me. Are you on the latest version (2.0.3)?

**Comment by kevboh** [comment]
Lastly, it's possible you got the plugin into some strange state and may need to restart the app, which you can do by running the "Reload app without saving" command. Try that after trying the above.

**Comment by anon3792737** [comment]
Just chiming in I use this plugin on my Ipad Pro + my Macbook + my Android phone, and it works great on all of them.

@Nunnyafbdjdj , is the plugin creating an index file in your project folder?

**Comment by Nunnyafbdjdj** [comment]
> Just chiming in I use this plugin on my Ipad Pro + my Macbook + my Android phone, and it works great on all of them.
> 
> @Nunnyafbdjdj , is the plugin creating an index file in your project folder?

Thank you for responding. I think part of the problem, and something I have to apologize to @kevboh about, is I’m not sure exactly what is supposed to happen. It looks like I right click and choose “Create Longform Project”. This prompts me to name my project. I then have nested items under that project which is a page named “Index”. When I click on that it takes me to a note titled “Index” and I’m not sure what to do from there. The reason I wanted to use the plug in is on the GitHub page it shows that there is supposed to be 3 columns and under that it prompts you to create a scene, I would like to have that, write my scene description in the box, and then be able to reorder the scenes to where they should go in the story. But I can’t seem to make it show the columns as shone in the screenshot. Can you give me an example of how you are using it on the iPad. I’m sorry if this takes a lot of time but it would be a great help.

**Comment by Nunnyafbdjdj** [comment]
> 

@kevboh    Greetings, I want to really apologize for my tone last week when requesting help. I was having trouble with all kinds of software that I was hoping would help me get my project off the ground, but seemed to run into problems with every tool I tried. But that is no excuse for taking such a disrespectful tone to someone who put a lot of work into something and putting it out for free. It seems like if I can get it work it would be something that is exactly what I was looking for, but again that is a terrible excuse for my behavior. A part of my frustration was it seemed like there were no resources for me to try to figure this out for myself, and when I can’t figure out something I get very frustrated, but I embarrassed myself here and acted like a child. I hope you will accept my apology. I did choose the sponsor option, because I feel that if I am able to get this to work for me, that the person that took the time to create a tool that helps me be more productive should be compensated and rewarded. So that will stay, but again, I’m very sorry for my behavior.  @kevboh

**Comment by anon3792737** [comment]
@Nunnyafbdjdj 

Ok, so the Index.md file is what the Longform plugin uses to identify which folder scenes are located in / order scenes / compile scenes etc.

Are you able to create a longform project on your computer?

**Comment by Nunnyafbdjdj** [comment]
> @Nunnyafbdjdj
> 
> Ok, so the Index.md file is what the Longform plugin uses to identify which folder scenes are located in / order scenes / compile scenes etc.
> 
> Are you able to create a longform project on your computer?

I don’t have Obsidian on my MacBook Pro, I don’t really use it. I primarily use my iPad for work. I guess I could try it later.

**Comment by kevboh** [comment]
@Nunnyafbdjdj no worries. I get it—software can be frustrating.

It's pretty hard to debug this without a clearer picture of what's happening on your iPad. Specifically, I'm still interested in what the contents of that `Index.md` are.

Did you try any of the suggestions I made above, like [this one](https://github.com/kevboh/longform/issues/139#issuecomment-1399239914)?

**Comment by Nunnyafbdjdj** [comment]
> @Nunnyafbdjdj no worries. I get it—software can be frustrating.
> 
> It's pretty hard to debug this without a clearer picture of what's happening on your iPad. Specifically, I'm still interested in what the contents of that `Index.md` are.
> 
> Did you try any of the suggestions I made above, like [this one](https://github.com/kevboh/longform/issues/139#issuecomment-1399239914)?

Thanks for understanding, I’m still pretty embarrassed and apologize again.

So I tried those steps that you referenced above. When trying to Run the "Insert multi-scene frontmatter" command (I went to the Index note and typed CMD + P and then chose “Insert multi-scene formatter”, it looks like nothing happened. 

When I go to the Index note and I copy and paste in that “frontmatter”, then when I go to the Longform pane there is a column called Scenes, and I’m able to insert new scenes. For a second I was able to drag scenes and reorder them, but I can’t seem to do that now.

If I have to do that to run it, do you suggest I create a note and paste that formatter into it and then when I create a new script I just copy and past it into the index of the new project?

And also, in the ‘project metadata’ it has a field for Title, and in that field is the word Index (I guess that is a link to the Index note/file) would that say the title of the project? or do I have to go to where it says “drafts” and choose the project that way?

**Comment by kevboh** [comment]
> When trying to Run the "Insert multi-scene frontmatter" command (I went to the Index note and typed CMD + P and then chose “Insert multi-scene formatter”, it looks like nothing happened.

Hmm. This exact series of steps works for me on my iPad Pro. In the long term perhaps I'll ship a "debugging mode" that logs everything to a file you can share with me, but for now I'm at a loss.

> When I go to the Index note and I copy and paste in that “frontmatter”, then when I go to the Longform pane there is a column called Scenes, and I’m able to insert new scenes. For a second I was able to drag scenes and reorder them, but I can’t seem to do that now.

Strange that reordering stopped working. If it helps, there are also commands to reorder scenes.

> If I have to do that to run it, do you suggest I create a note and paste that formatter into it and then when I create a new script I just copy and past it into the index of the new project?

If you'd like. I'm also curious what right-clicking on an empty folder and choosing Create Longform Project and following the steps gets you. It should create the right stuff.

> And also, in the ‘project metadata’ it has a field for Title, and in that field is the word Index (I guess that is a link to the Index note/file) would that say the title of the project? or do I have to go to where it says “drafts” and choose the project that way?

That's the title because it defaults to the name of the index file. You can edit that field to change the title. Longform tries to give you tools to avoid editing the index file directly, and you should use them (if they work!)

**Comment by kevboh** [comment]
I'm going to close this issue as it seems particular to your case, even though we haven't quite figured it out yet. Feel free to keep commenting here for help.
