### ISSUE TITLE
FR: Add wordcount of all scene-notes to their yaml-header

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#14]
This could be very interesting, since then you could very easily create a table with the wordcount of every scene via dataview. Doing so also would not be very hard, as it is basically prepending the results of [wc](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/wc.1.html) on every file. 

...however, it would also entail to remove yaml-headings during compile 😕

**Comment by kevboh** [comment]
I don't want to be in the business of editing notes directly, so this in particular is out of scope. However, as noted in the README, I'd like to see where [this feature request](https://github.com/lukeleppan/better-word-count/issues/22) goes and then add per-scene, -draft, and -project word counts from there.

**Comment by chrisgrieser** [comment]
btw, I found a "workaround" via dataview. Dataview does not count characters, but is does count bytes, which are roughly similar to characters. And taking estimations that the[ average word length of an English word ist 4.79](http://norvig.com/mayzner.html), is possible estimate the characters and words of a draft.

```
TABLE file.size as "Character Est.", round(file.size / 4.79) as "Word Est. (English)"
FROM "Draftfolder"
SORT file.size DESC
```
Only issue is that the scenes do not appear in the same order as in longform.

![Screenshot 2021-08-11 16 58 35](https://user-images.githubusercontent.com/73286100/129053094-6dcbb2e5-fc40-4038-93f2-07223ce6bcc2.png)
