### ISSUE TITLE
Feature Request: Allow Save as Note compile step to save the note in non-relative folders

### ISSUE THREAD

**Issue by matthewmerendo** [kevboh/longform#143]
**Describe the solution you'd like**
Currently, when you save a manuscript as a note, you can specify a folder **relative to the project** in which to save that note. I'd like to be able to choose a folder outside of the project, relative to the root of the vault.

**Describe alternatives you've considered**
I've tried using a front slash, as well as .. syntax, but nothing seems to work.

**Comment by kevboh** [comment]
Makes sense, easy to implement if we check for a leading slash. Thanks.

**Comment by b-camphart** [comment]
Oh, I think this should be possible now with #187 having been merged.

**Comment by matthewmerendo** [comment]
> Oh, I think this should be possible now with #187 having been merged.

With front-slash or .. syntax?

**Comment by b-camphart** [comment]
Should handle both.

**Comment by matthewmerendo** [comment]
Yep, we're good now on this one!
