### ISSUE TITLE
First project's index seems to be overwritten with second project's index file...?

### ISSUE THREAD

**Issue by EdualcLaiv** [kevboh/longform#15]
Hello, 

- when I create my first project, I can't create drafts or scenes.
- if I create several projets, the first is broken. Others are alright.

No matter what I do then, my first project's index is always the same as my second project's index file.

I made a video showing in a more detailed way what I'm experiencing :
https://youtu.be/lcjryLTHaeU
(sorry for my dumb voice and terrible accent)

If needed, my zipped vault: [Test.zip](https://github.com/kevboh/longform/files/6964562/Test.zip)

**Comment by kevboh** [comment]
1. You don't have a dumb voice and don't need to apologize for it.
2. Thanks for the report. I think I know what this is—the Svelte store isn't properly updating on initial install. I'll chase it down, thanks again.

**Comment by kevboh** [comment]
Okay, watching your video which is _very_ helpful. This is a pretty bizarre bug, I haven't seen it before. Thanks for reporting.

**Comment by kevboh** [comment]
This will be fixed in the next update. Thanks again for your report, it was exactly what I needed to pin this down!

**Comment by kevboh** [comment]
@EdualcLaiv try 1.0.3, just released.
