### ISSUE TITLE
Does longform still have an issue with plist files?

### ISSUE THREAD

**Issue by wc8** [kevboh/longform#150]
I am considering trying Longform, but I actually use Notebooks to sync my Obsidian vault, so I am wondering if I would run into an issue if plist files are created:

       
"... - In moving projects over from Notebooks app to Obsidian, I at first ran into problems with longform because Notebooks app creates a plist file for each scene, and longform didn't know what to do with these files. Once I learned to delete the plist files before designating a longform project, I was fine
..."

_Originally posted by @pdworkman in https://github.com/kevboh/longform/issues/35#issuecomment-1002690147_

**Comment by pdworkman** [comment]
Longform now has a feature to allow you to ignore files placed in the draft folder, so that may solve the plist problem. ie., tell it to ignore each of the plist files.

**Comment by kevboh** [comment]
It also accepts wildcard characters, so you could add something like `*.plist` to `ignoredFiles`. Let me know if that doesn't work and I'll reopen this issue.
