### ISSUE TITLE
Question: Are there any known issues with Scrivener external folder sync

### ISSUE THREAD

**Issue by wc8** [kevboh/longform#153]
Is it known whether longform and Scrivener External Folder Sync, can work together?

**Comment by kevboh** [comment]
I'm not sure what that is. If it generates markdown, then sure! My experience with Scrivener is that it generates its own proprietary format. Either way, supporting Scrivener's output is not within the scope of this plugin.

**Comment by wc8** [comment]
Thank you. Scrivener's _External Folder Sync_ can be told to output to .md. 
I had my first chance to experiment with the plugin yesterday, and it's a little different from what I expected but intriguing. Though I am not really sure I understand it yet. I guess rereading the docs is in order. Thanks for your time. 
(I hope this reply doesn't reopen the "issue". I'm not very familiar with github.)

**Comment by kevboh** [comment]
You're good! Thanks for trying it out.
