### ISSUE TITLE
Unable to select notes within Longform

### ISSUE THREAD

**Issue by The-Grand-Vizier** [kevboh/longform#155]
Hi, I have a weird issue where once I have created a new note in Longform or imported a new note, when I click on it to select it in the sidebar, it highlights as if I am long-clicking or “grabbing” the note to move or rearrange it. This means I can’t actually click on any note to select it to edit it, as it assumes I’m trying to grab and move it as soon as I click on it. 

I found I can sometimes get to select it if I am able to click-hold-move my mouse and then release it when it’s moused over the text (the text indents and moves down from the standard position when it’s “grabbed” and ready for moving, so makes it hard to actually mouse over the text). 
Most often the note moves with the mouse moments though, so I generally can’t get that right. 

I am using latest obsidian version. 
Using Minimal Theme.

**Comment by kevboh** [comment]
Interesting, thanks for filing. I'll take a look. Sometimes with custom themes it can be hard to reproduce the issue, or the issue stems from the theme, so I may be unable to fix.

**Comment by The-Grand-Vizier** [comment]
Thanks! 
I’ve now tried it with multiple themes, as well as the default, and the issue persists. 
Doesn’t matter how “indented” I move the note, I still can’t click on it. 

I’m on a Mac if that makes a difference (I know nothing about code 🤷). 

If there is any other info you may need let me know, as I’d love to use your plugin for the book I’m writing. 
Currently the only way I can switch between notes within the Longform tab is by using the quick switcher, which is too cumbersome for me.

**Comment by PhilippSmolka** [comment]
Same here, also on a Mac. Unfortunately this a show-stopper.
Wish I could help more.

**Comment by slowdive14** [comment]
> Thanks! I’ve now tried it with multiple themes, as well as the default, and the issue persists. Doesn’t matter how “indented” I move the note, I still can’t click on it.
> 
> I’m on a Mac if that makes a difference (I know nothing about code 🤷).
> 
> If there is any other info you may need let me know, as I’d love to use your plugin for the book I’m writing. Currently the only way I can switch between notes within the Longform tab is by using the quick switcher, which is too cumbersome for me.

I had the same problem. In my case, if I right-clicked and then left-clicked, it clicked fine.

**Comment by b-camphart** [comment]
Confirmed on Windows too.  Installing cMenu immediately makes this bug appear.  Disabling it fixes it.

**Comment by slowdive14** [comment]
I was using the cMenu and disabling it solved it. Thank you.

**Comment by kevboh** [comment]
Great. I'll (eventually) install cMenu to see if I can figure out the issue.

**Comment by b-camphart** [comment]
Looking into this further, it looks like cMenu uses sortablejs for their settings window, allowing the user to reorder the style buttons.  I haven't quite figured out why both plugins being active makes Longform's Sortable plugin change behavior, but cMenu seems to be fine.  Still looking into it.

**Comment by b-camphart** [comment]
I discovered the source of the issue and have opened a PR to resolve it.  I also submitted a new ticket with cMenu to let them know that they are causing conflicts, and might also be subject to conflicts themselves.
