### ISSUE TITLE
Added or renamed note won't stay added

### ISSUE THREAD

**Issue by Davidjl50** [kevboh/longform#160]
**Versions**
Longform version: 2.0.3
Obsidian version: 1.1.16
OS [e.g. macOS, Windows, iOS, Android]:  Windows, Linux
Theme:
no matter

**Describe the bug**
I needed to change the name of one of my notes, now every time when I boot up I have to add it and place it where it supposes to be

**Comment by kevboh** [comment]
hmmm, strange. Longform specifically listens for rename hooks for this reason. Do you use Obsidian sync? What does the project's yaml look like?

**Comment by Davidjl50** [comment]
Thanks for answering, I do not use Obsidian sync. Where is the project yaml at? Is that the same as the index? I just check the index and the index still has the old name of the note. How do you update it?

**Comment by kevboh** [comment]
Yes, the index. You can edit it directly. My random guess is that whatever you're using for sync restored the old index.

**Comment by Davidjl50** [comment]
I have my files on Google Drive, so I can access it from different devices. Thanks, I will edit the index.
