### ISSUE TITLE
Failed to load plugin longform

### ISSUE THREAD

**Issue by froses** [kevboh/longform#162]
**Versions**
Longform version: 2.0.3
Obsidian version: Mobile version 1.4.4 (99) API v.1.2.7
OS [e.g. macOS, Windows, iOS, Android]: iPadOS
Theme: Default
Other plugins that you think might be relevant here:

**Describe the bug**
When I start Obsidian "Failed to load plugin longform" error message is displayed. 

No problems loading Longform with the previous Obsidian Mobile version.

Logform seems to work fine with Obsidian Mac, Windows, and iOS but fails in iPadOS 16.4.1(a).

**To Reproduce**
1. Open Obsidian Mobile on an iPad Pro 2023 (iPadOS 16.4.1(a)

**Expected behavior**
No error message displayed.

**Screenshots**

**Additional context**

**Comment by kevboh** [comment]
Thank you for this detailed report! I'll try to take a look in the next couple of days. Debugging on mobile is very difficult.

**Comment by froses** [comment]
Thanks for your excellent work! 

Francesc

**Comment by kevboh** [comment]
Is this still happening? I suspect it's a metadata issue. Closing, comment if still happening. Thanks!
