### ISSUE TITLE
Bug: Sync issues

### ISSUE THREAD

**Issue by novakwh** [kevboh/longform#167]
I have the latest Obsidian, Longform, Mac OS, iOS, Android. I use Obsidian Sync and continually have sync issues with Longform essentially losing updates to the index file in a project. So I have to keep clicking "add" when it finds scenes, and then I have to put them all back in order, which gets pretty frustrating the longer a project gets. I am syncing between Obsidian on my Mac, my iPad, and my Android phone. There are no other sync issues in my vault, it only affects Longform.

**Comment by kevboh** [comment]
Hi, thanks for using Longform.

This is a consequence of how Sync works, and is pretty much out of my control. Sync does not provide API-level hooks to inform plugins of when sync or conflict resolution are happening, which means that in Longform's view you are just changing files and it is duly updating as if you're working on a single machine. There is no difference from a plugin perspective between "normal" edits and synced ones.

The best way to mitigate this is to watch the Sync log whenever you switch to a new device and wait until it is totally resolved before touching anything. Not ideal, but the best we can do in this case.

I may be able to help more with this problem in a few weeks with a different plugin I'm working on—watch this space.

**Comment by erazlogo** [comment]
I have the same issue--one manual way to get around it is to choose Select Sync Version History on the Index file and go back to the version that has all the notes included and sorted.

**Comment by kevboh** [comment]
Yeah, again, this is a Sync issue, not a Longform one. Going to close this.
