### ISSUE TITLE
Feature Request: Command to Run Compile

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#170]
**Describe the solution you'd like**
Add a command to the command palette for running the currently configured compile workflow. Then, with the advanced URI plugin, you can trigger a compile programmatically and for example combine it with a makefile or a shell script also running pandoc.

This would allow you to create a finished end product with just one trigger, enabling things like live updating your paper in Obsidian. (see this example without the longform plugin, where someone live-updates their latex project as soon as changes in the Obsidian vault are detected: https://discord.com/channels/686053708261228577/722584061087842365/1116257946398117898)

**Describe alternatives you've considered**
Can't think of any to achieve this with the longform plugin.

---

Optionally, you can also add a URI to trigger the compile step, since it's something people would commonly want to trigger from outside Obsidian, removing the advanced URI plugin as dependency for that kind of workflow.

**Comment by chrisgrieser** [comment]
also, the compile step request for export via pandoc (#142) might also be relevant for this to streamline the process

**Comment by kevboh** [comment]
Makes sense!
