### ISSUE TITLE
Remove scene from "Scenes" list

### ISSUE THREAD

**Issue by AndrewMWebster** [kevboh/longform#173]
As a Longform user
I want to be able to remove files added in error to the Scenes list
So that irrelevant matter will not be included when compiling.

I almost logged this as a bug, but it's not something that's not working - it's something that's missing!  

It's very easy to accidentally add a file to the Scenes list.  But afaik it's impossible to remove it, without manually editing the index file.  It seems risky to rely on "going behind the scenes" to resolve a mistake.

**Comment by kevboh** [comment]
So you can do this now by ignoring the file--add it to the ignoredFiles list in your index, and remove from scenes.

I'll leave this ticket open for adding UI to do this, but this sort of index editing us totally fine.

**Comment by AndrewMWebster** [comment]
Grand.  A UI would definitely make it slightly less nerve-wracking.  While the joy of Obsidian is that so much is tucked away in plain(-ish) text, that's also the danger of it!

**Comment by kevboh** [comment]
Closed by referenced PR.
