### ISSUE TITLE
Remove comments on compile

### ISSUE THREAD

**Issue by AndrewMWebster** [kevboh/longform#175]
Request:
Have an option to remove comments from scene files on compilation.
I've got two simple use-cases for this.  
1. In-line comments.
2. Endmatter comments.

When writing longer pieces, it's useful to be able to put in comments as a reminder, say, where there's a set-up in one scene and an intended pay-off in a later scene.  On compilation, it would be helpful if it was optional to include the comments.

For endmatter, commented sections are useful for, say, links that refer to research, to other scenes in the same arc, etc.  Links are not helpful in frontmatter currently (the graph view, for instance, ignores them).  Again, they should probably not be wanted in a compile manuscript.

Alternative:
Using tricky find and replace regex in a separate text editor.  This is a pain!

**Comment by kevboh** [comment]
Does the `Remove Comments` step not work for you?

**Comment by AndrewMWebster** [comment]
Oh crap!  Apparently I might be able to write, but not read.  Yes, the Remove Comments step works.  Apologies!
