### ISSUE TITLE
Bug: Longform loses track of project folder

### ISSUE THREAD

**Issue by apolaine** [kevboh/longform#176]
**Versions**
Longform version: 2.0.3
Obsidian version: 1.3.7
OS [e.g. macOS, Windows, iOS, Android]: Mac OS 13.4.1
Theme: None
Other plugins that you think might be relevant here: Lots of these, difficult to pin down an interaction

**Describe the bug**
I have a multi scene Longform book project that has been working fine so far, but when I opened it today, the plug-in no longer sees the project folder as a project. I just get the getting started text when I click on the Longform tab. The Index.md file is still there and seems intact. So does the data.json, though I'm not entirely sure what I'm looking for.  

**To Reproduce**
This seems random at present. I can't reproduce it at will.

**Expected behavior**
Expect the Longform project remains marked as a Longform project.

**Additional context**
I'm running my vault on iCloud, but using Obsidian Sync. This has been fine for me for ages and I don't see any evidence of race conditions or file duplicates.

Is there any way to "reconnect" the Project to Longform without having to rebuild it manually by adding and reordering all the individual files again?

**Comment by kevboh** [comment]
Can you email me your data.json and a copy of the relevant index.md file? kb@kevinbarrett.org

**Comment by apolaine** [comment]
Sure. I'll send it over now.

**Comment by kevboh** [comment]
This was fixed over email—an issue with incorrect indentation in the index file, likely as a result of competing sync services (but no way to know for sure).
