### ISSUE TITLE
1.0.3: After unmarking and deleting another Longform folder, remaining isn’t accessible, shows wrong data.

### ISSUE THREAD

**Issue by Moonbase59** [kevboh/longform#18]
I created a second Longform folder, "Great American Novel", to check issues in #17.

After checking and all was running again, I

- unmarked "Great American Novel" as a Longform folder, then
- deleted it in file explorer, then
- came back to the Longform pane.

My previous "Longform test" is still shown, but with a subheader (file path) of "Great American Novel/Draft 1" and I cannot select any of the 5 drafts that are _really_ in "Longform test".

![Auswahl_125](https://user-images.githubusercontent.com/3706922/129106699-85d13eb3-b658-43ed-b159-43487ab3d378.png)

**Comment by kevboh** [comment]
Ah, I think I know what this is. If you unmark/delete a project while it's selected in the pane, data desyncs. I'm assuming that's what you did, @Moonbase59?

**Comment by Moonbase59** [comment]
Like "Longform test" above? Yup, then I did.

**Comment by kevboh** [comment]
Closing, please reply if this was never resolved and I will reopen and try to help further.
