### ISSUE TITLE
Bug: Misleading instruction in Longform tab

### ISSUE THREAD

**Issue by leoleoimn** [kevboh/longform#182]
**Versions**
Longform version: 2.0.3
Obsidian version: 1.3.7
OS: Windows

**Describe the bug**
When you currently hold no Longform projects, an instruction will erroneously tell you to "Mark [a folder] as Longform project."

**To Reproduce**
1. Create a new vault or sandbox vault. Essentially, this ensures you have no existing Longform projects.
2. Install Longform.
3. Click on the Longform tab.

**Expected behavior**
Either removing this instruction or providing a clearer instruction would be more beneficial.

**Screenshots**
![image](https://github.com/kevboh/longform/assets/71240029/abb46d6e-2e59-4b5e-9e77-6c45b51e501f)
![image](https://github.com/kevboh/longform/assets/71240029/f7eb246f-a229-4809-a9fb-0469fea26f51)

**Comment by kevboh** [comment]
Ah, thanks, must've missed it.
