### ISSUE TITLE
Bug: Longform lose project order every time I logout of Obsidian

### ISSUE THREAD

**Issue by Krisztin82** [kevboh/longform#193]
**Versions**
I just downloaded it today so the newest one
Windows

**Describe the bug**
I spent 3 hours uploading my project. I closed Obsidian and when I turned it on again while the files are there, there is nothing in logform just the empty project. I thought I did something wrong so I did it again, but it happened again.

There is only two other community plugins are instaled: Dataview and Novel Word Count

**Comment by b-camphart** [comment]
Can you screenshot or upload what your index.md file looked like before you closed obsidian, then another after?  It'll be helpful to know if the index.md file is getting overwritten, or if it just isn't being read properly.

**Comment by Krisztin82** [comment]
Hello,
I can't send you the before picture (or if you can tell me how can I go
back in file history or something I am willing) but I attached the now.

**Comment by kevboh** [comment]
Thanks. If this happens again, please reopen this issue and share any errors in the console (cmd-shift-i).
