### ISSUE TITLE
I have no `New Scene` field...

### ISSUE THREAD

**Issue by lillian-who** [kevboh/longform#20]
I have no `New Scene` field...

<img width="352" alt="image" src="https://user-images.githubusercontent.com/20553685/130310364-ab48a0ad-45c5-4bff-b46a-00602a98ea4e.png">

**Comment by kevboh** [comment]
@YaRauy Can you share the project's Index file? I'd also suggest restarting Obsidian, there's a bug I haven't nailed down yet where state can desync.

**Comment by YaRauy** [comment]
> @YaRauy Can you share the project's Index file? I'd also suggest restarting Obsidian, there's a bug I haven't nailed down yet where state can desync.

Hi, I've restarted Obsidian several times, but still.

**Comment by kevboh** [comment]
> > @YaRauy Can you share the project's Index file? I'd also suggest restarting Obsidian, there's a bug I haven't nailed down yet where state can desync.
> 
> Hi, I've restarted Obsidian several times, but still.
> 
> There is my project's Index file:
> 
> <img alt="image" width="154" src="https://user-images.githubusercontent.com/20553685/130329809-4e195046-97b3-4da1-ae49-405000ab2544.png">

Sorry, I meant the contents of the Index file—if it's malformed, Longform won't know what to do for that project.

**Comment by YaRauy** [comment]
> 
> 
> > > @YaRauy Can you share the project's Index file? I'd also suggest restarting Obsidian, there's a bug I haven't nailed down yet where state can desync.
> > 
> > 
> > Hi, I've restarted Obsidian several times, but still.
> > There is my project's Index file:
> > <img alt="image" width="154" src="https://user-images.githubusercontent.com/20553685/130329809-4e195046-97b3-4da1-ae49-405000ab2544.png">
> 
> Sorry, I meant the contents of the Index file—if it's malformed, Longform won't know what to do for that project.

My Index file is empty.

**Comment by kevboh** [comment]
Closing, please reply if this was never resolved and I will reopen and try to help further.
