### ISSUE TITLE
Feature Request: When adding a file in Obsidian, we could choose a template.

### ISSUE THREAD

**Issue by kickTiger** [kevboh/longform#204]
I want to express my sincere gratitude to the plugin's author. 
Your plugin is absolutely fantastic and it's become a daily essential for me.

**Describe the solution you'd like**

I have a suggestion regarding the "scenes" feature. It would be wonderful if, **when adding a new file in Obsidian, we could choose a specific template**, like "`Add new scene below: Templater`". 

Combining this with the left-hand file list's "`Create new note from template`" feature would be fantastic.

I appreciate that there's currently the ability to set both global and project-specific templates, which is great. However, I would like to suggest the smaller feature I mentioned earlier.

**Comment by kevboh** [comment]
Hi! This feature exists: use the "Scene Template" field in the Projects tab.

**Comment by kickTiger** [comment]
Thank you for your response. I'm familiar with the functionalities you mentioned, and I'm currently using them.

Perhaps I didn't express myself clearly. What I mean is:

1. Within Scenes, the ability to invoke other templates defined in the template plugin, as sometimes I need to insert different file contents.
2. Not relying on the templates pre-set in the Project, as that allows only a fixed template.

**Comment by kevboh** [comment]
I see. How would this different from creating a blank scene and then using Templater commands to insert the appropriate template? My preference is to avoid re-implementing other plugins where possible.
