### ISSUE TITLE
Feature Request: Chapter object that automatically transcludes the scenes within it

### ISSUE THREAD

**Issue by adsilcott** [kevboh/longform#208]
**Describe the solution you'd like**
I think Scrivener had a feature like this, where if you put your pages in a folder and clicked on the folder, it would show the contents of all of the pages it contained concatenated together on one page. It was great for getting a sense of how sections of a chapter flow together at a glance.

**Describe alternatives you've considered**
I can manually transclude scenes in a parent scene file, but it doesn't really format the way I want it to, it kind of defeats the purpose of being able to easily drag scenes around to reorder them in the sidebar, and it might mess with compilation.

**Comment by b-camphart** [comment]
I'm imagining the ability to click on a "parent" scene and focus compilation just on that section.

**Comment by kevboh** [comment]
Yes, I have long wanted this, as I used it a lot in Scrivener. Obsidian makes this difficult to do without effectively reimplementing the editor view, unless I've missed some clever solution. Open to ideas!

(Also pretty sure this issue already exists, but couldn't find it in a cursory search so leaving open for now)

**Comment by kevboh** [comment]
Found it: #131
