### ISSUE TITLE
I would suggest adding an archiving f eature

### ISSUE THREAD

**Issue by kickTiger** [kevboh/longform#210]
**Describe the solution you'd like**
I would suggest adding an **archiving** f eature, which means changing the status of a "longform" project to "archived" when it's either completed or temporarily not being edited. Here's how it can be done:

1. You can add a new attribute in the YAML section to avoid listing the archived projects in the longform list.
2. You can choose to archive the main "longform" project along with its corresponding draft projects, or simply archive individual versions.
3. In the longform plugin settings, you should also have the option to restore a project to its normal status.
4. The advantage of this is that it allows you to archive projects that are not currently being edited, preventing them from cluttering the longform display list but still retaining their status. This makes it convenient to continue editing or modifying them when the time is right.

In a recent update of the **project** plugin, they introduced this feature. Archiving and restoring, I believe, could be a valuable addition to the longform plugin, especially since my longform contains numerous projects that could benefit from such an archiving function.

**Comment by kevboh** [comment]
I like this. I would probably simplify to just a property that's hidden in Longform if set to the archived value, and people can change that property manually themselves. Thanks for filing.

**Comment by kerim** [comment]
I would like to have archived projects, or the ability to simply test a compile first. I was surprised that compiling destroyed the project because I was just testing it out and wasn't done with my project...

**Comment by kevboh** [comment]
@kerim compiling shouldn't destroy the project....it's possible you set the compiled output to be the same name as your index file, which would overwrite it (and is not something one should do).

**Comment by kerim** [comment]
I see, that's probably what happened. But other steps are destructive no? For instance, if I have it set to clear out %%notes%% before processing, those will be gone, there is no way to save a version of that document that retains the notes?

**Comment by kevboh** [comment]
No, no steps are destructive. They only apply to the final, compiled output.

(Closing this, though we can continue talking this through!)
