### ISSUE TITLE
Add hotkey to keep focus on New Scene text input when adding new scene

### ISSUE THREAD

**Issue by thesamim** [kevboh/longform#214]
**Describe the solution you'd like**
When adding new scenes in the longform panel, it would be useful to be able to add multiple scenes at a time, instead of clicking on "New Scene" every time to start the next add.

eg: 
1. Click on "New Scene"
2. type in scene name
3. hit enter
4. Focus automatically goes to "New Scene"
5. Start typing again

**Describe alternatives you've considered**
Only alternative is to keep clicking....

**Comment by kevboh** [comment]
Hmm. I think the most common thing a person would want to do after naming a scene is edit it, similar to how Obsidian works with note creation. Perhaps a hotkey, e.g. cmd-enter, could keep focus?

**Comment by thesamim** [comment]
> Hmm. I think the most common thing a person would want to do after naming a scene is edit it, similar to how Obsidian works with note creation. Perhaps a hotkey, e.g. cmd-enter, could keep focus?

That would work.

The specific use case was: I'm starting a work, I know what the scenes are going to be, I just wan to enter all of them now. Start writing once I have that outline.

**Comment by kevboh** [comment]
This will be available in the next release.
