### ISSUE TITLE
unable to enable on new install

### ISSUE THREAD

**Issue by deminou** [kevboh/longform#215]
**Versions**
Longform version: 2.0.4
Obsidian version: 1.4.16
OS [e.g. macOS, Windows, iOS, Android]: chromeos
Theme: default
Other plugins that you think might be relevant here: n/a

**Describe the bug**
After installing the plugin, receive error "Failed to install plugin longform".

**To Reproduce**
1. Go to Obsidian Settings
2. Click on Community plugins
3. Click to enable Longform plugin

**Comment by kevboh** [comment]
Is there an error in the console if you turn on dev tools in Obsidian? View > Toggle Developer Tools

**Comment by kevboh** [comment]
Closing; if this is still happening, please comment with the error.
