### ISSUE TITLE
Support subdirectories in longform project directory

### ISSUE THREAD

**Issue by mremond** [kevboh/longform#217]
I am writing a fairly large project, with several parts and many chapters.

I am keeping my file in a directory structure, but it seems that if I move that structure in the longform projet dir, longform will not detect new files or more precisely offer to add them with the name undefined. When I click it, it creates the file title "undefined".

I am not sure if this is a bug or simply a missing feature.

**Comment by kevboh** [comment]
Duplicate of #125. Not a thing supported right now.
