### ISSUE TITLE
Word count continues to count up after reaching goal. 

### ISSUE THREAD

**Issue by kingcody2791** [kevboh/longform#222]
Currently, the word count stops counting up once you have reached your goal. I.E. if your goal is 500 words it will reach 500/500 words, and count no further. With this set-up there is no way to tell how many words you have written in a session once you have reached your goal. My request is for your session word count to continue to rise once you have reached your goal. I.E. 775/500.

Alternatively, the ability to see the word count of a highlighted selection would be nice, such as ctrl+shift+C in google docs.

**Comment by gmatthies** [comment]
I'd like to chime in and add my support for this. I've noticed that if you increase the goal from 500 to 1000, then using @kingcody2791's example, you'll see 775/1000. So, it looks like Longform already has this information and just needs to show this in the Word Count numerator.
