### ISSUE TITLE
Feature Request: Use obsidian search syntax to match scenes

### ISSUE THREAD

**Issue by b-camphart** [kevboh/longform#224]
**Describe the solution you'd like**
Obsidian provides a query syntax for finding files which is used to search, but also to filter/group nodes within a graph.  As a possible way of making Longform more unified with Obsidian, and making scene selection more flexible, I propose using this query syntax as an alternative method of supplying scenes.

Additionally, this would prevent needing to exclude scenes, and possibly even open up easier ways of building new features that require checking if a scene matches some criteria (compilation omission, for example).

I propose having a new item in the index file to specify a search query to include matching scenes in the draft.  
The syntax would follow the specifications here: https://help.obsidian.md/Plugins/Search

To make this change easier (and because I needed it for my own plugin) I've already written a [library for recreating the search functionality.](https://github.com/b-camphart/obsidian-search/)  However, it doesn't _fully_ adhere to the above specifications, but it has most of them.  So, the difficult part of building this has already been completed :)

**Comment by kevboh** [comment]
This is a fun idea that I think is a bit too much investment before the Obsidian team's databases/dynamic views work is unveiled. My hope is that that work will feed into a more holistic and reactive metadata system that will enable more flexible Longform indexing.
