### ISSUE TITLE
reference material

### ISSUE THREAD

**Issue by kerim** [kevboh/longform#225]
I'd like to add documents that are simply notes I am referencing, or deleted bits of text from my scenes. These would be part of the project but aren't scenes and so would be ignored when the document is compiled. (But should be preserved somehow afterwards - see the related request for an archive function.)

**Comment by kevboh** [comment]
This was the original motivation for building Longform: your vault itself is your reference material. I'm not sure where nondiegetic text would go within a project. I personally open research notes in panes alongside whatever I'm writing.
