### ISSUE TITLE
Bug: TypeError: Cannot read properties of null (reading 'format')

### ISSUE THREAD

**Issue by devinat1** [kevboh/longform#226]
On a new install of longform, I am getting the following error: TypeError: Cannot read properties of null (reading 'format')

Full error:
![image](https://github.com/kevboh/longform/assets/15788108/cab3b3e1-a3ee-4617-9874-1b43f6e420d7)

Debug info:
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.23606
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.4.6
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 45
	Plugins enabled: 33
		1: Admonition v10.1.1
		2: Calendar v1.5.10
		3: Custom Frames v2.4.6
		4: Dataview v0.5.64
		5: Dice Roller v10.4.0
		6: Editor Syntax Highlight v0.1.3
		7: Excalidraw v2.0.12
		8: Google Photos v1.6.5
		9: Hider v1.3.1
		10: Homepage v3.6.0
		11: Image Toolkit v1.4.1
		12: LanguageTool Integration v0.3.6
		13: Linter v1.22.0
		14: Minimal Theme Settings v7.3.1
		15: Note Refactor v1.8.2
		16: Obsidian_to_Anki v3.4.2
		17: Paste URL into selection v1.7.0
		18: Plugin Update Tracker v1.5.2
		19: Quick Switcher++ v3.3.9
		20: QuickAdd v1.6.1
		21: Readwise Official v2.0.1
		22: Recent Files v1.3.8
		23: Settings Search v1.3.10
		24: Templater v2.0.0
		25: Text Extractor v0.4.10
		26: Todoist Plugin v1.11.1
		27: ExcaliBrain v0.2.11
		28: DB Folder v3.5.0
		29: Zotero Integration v3.1.2
		30: Citations v0.4.5
		31: Pandoc Reference List v2.0.24
		32: Pandoc Plugin v0.4.1
		33: Longform v2.0.4

**Comment by kevboh** [comment]
@devinat1 can you either paste here or email me (kb@kevinbarrett.org) your index file? It is likely malformed.

**Comment by devinat1** [comment]
> @devinat1 can you either paste here or email me (kb@kevinbarrett.org) your index file? It is likely malformed.

How do I find the index file?

**Comment by kevboh** [comment]
@devinat1 it's the file in your longform project typically called something like `Index.md` that has a `longform` property with a bunch of YAML in it.

**Comment by kevboh** [comment]
Could you test with 2.0.6 and let me know if this is still happening?

**Comment by kevboh** [comment]
Oh weird, this is coming from kanban. Okay, good to know, will look into it.

**Comment by kevboh** [comment]
When does this happen? Are you doing anything in kanban when you see it?

**Comment by devinat1** [comment]
Nope I am doing nothing with kanban.

**Comment by devinat1** [comment]
It happens randomly as I am using obsidian regularly, regardless of what I am doing.

**Comment by kevboh** [comment]
You do have kanban installed, though?

**Comment by kevboh** [comment]
I think I figured this out. It should be fixed in the next release. In the meantime I don't think the error will actually affect functionality, but let me know if you notice anything aside from the error in the console.
