### ISSUE TITLE
Bug: 2.0.5 fails to install

### ISSUE THREAD

**Issue by lazyguru** [kevboh/longform#230]
**Versions**
Longform version: 2.0.5
Obsidian version: 1.5.3
OS [e.g. macOS, Windows, iOS, Android]:  macOS
Theme: N/A
Other plugins that you think might be relevant here:

**Describe the bug**
Longform fails to update from 2.0.4 to 2.0.5. I'm fairly certain this has to do with the package-lock.json file [not being updated](https://github.com/kevboh/longform/blob/0b82b1a9700ad4fb119ec0db4a22547bba7877ad/package-lock.json#L3) after the version was updated in package.json and before packaging.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Community plugins'
3. Scroll down to 'Longform'
4. Click on "Update"
5. See notification "Installing plugin 'Longform'
6. See notification "Failed to install plugin 'Longform'"

**Expected behavior**
Latest version of Longform should install

**Comment by lazyguru** [comment]
FYI, using BRAT I was able to update to the unreleased 2.0.6 so when that is released this issue would be resolved

**Comment by PupupupuTong** [comment]
New users are also unable to install

**Comment by Drakemoor** [comment]
I have the same issue.

**Comment by stervel** [comment]
This didn't happen with other plugins and I can confirm https://github.com/kevboh/longform/issues/230#issuecomment-1901732659 method works.

**Comment by kevboh** [comment]
Bleh! Thanks for catching. Fixing…

**Comment by kevboh** [comment]
This is now fixed with 2.0.6. Sorry about that!

**Comment by lazyguru** [comment]
I confirm it is fixed 😄

**Comment by Drakemoor** [comment]
thank you
