### ISSUE TITLE
Feature Request: virtualized file organization using canvas

### ISSUE THREAD

**Issue by Zplusless** [kevboh/longform#231]
**Describe the solution you'd like**
Longform has provided excellent writing experiences. However, it lacks an effictive way to organize notes and cards in obsidian. Such an issue could be solved by providing Visualize Mind which combines longform with obsidian canvas. This idea comes from [lattics](https://lattics.zineapi.com/en-us), which introduce itself as "Brain-like Knowledge Management Notes". I have checked the main features of lattics and found that the main difference between lattics and obsidian  longform is "orginazing files in a virtualized way". That is, the files can be arranged in a mindmap.  The good news is that obsidian has provided canvas, which records nodes and edges of a cavans in json. It would not be complicated to convert a ".canvas" file into the index file of a longform project.

So there are two possible workflows:

First:  New project with an index file ----> create new scenes, the scenes could be single file like current version of longform, or it could be an .md file and a .canvas file with the same file name. Writers can organize cards and notes in canvas ---> compile canvas into scenes by concatenating cards in the .canvas file ---> compile the project according to the index file.

Second: replace the current index file with an .canvas file. In this mode, the whole project could be organized in a virtulized way(like lattics).

**Describe alternatives you've considered**

**Comment by kevboh** [comment]
This is effectively #148, so I'm going to close this issue and count it as a vote there. Thanks for filing! It's a complicated ask, and something I don't plan on working on soon but would like to add one day.
