### ISSUE TITLE
Index in 2.05 only shows in json syntax

### ISSUE THREAD

**Issue by bissjoe** [kevboh/longform#232]
**Versions**
Longform version: 2.05
Obsidian version: 1.5.3
OS: Windows 10
Theme: Light? ("Clair" in French)
Other plugins that you think might be relevant here:

**Describe the bug**
I created two scenes in longform. When I click on the index, I don't see these scenes in a bullet-style list. Instead, they are within a JSON element in the Properties section at the top. All the information of the JSON element is displayed on a single line, which makes it difficult to read and to distinguish between the scenes.

Could it be that longform does not support the French language (my native language)?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by b-camphart** [comment]
This is due to how Obsidian renders properties now.  To edit the longform object, you'll have to edit it in source mode.

**Comment by bissjoe** [comment]
So the index note has no content, except the metadata in the properties?
If so, I suppose I should never bother to open the index note, but instead to use only the Scenes tab in the longform left panel?

Moreover (maybe I should fill another issue for this), when I tried to reorder the scenes from the Scenes tab, it didn't work and then it corrupted the index note's metadata (the two scenes disappeared from the JSON element).

**Comment by bissjoe** [comment]
Oops! Forget about the last comment about the reordering of the scenes. I didn't use the Scenes tab within longform, I use the native file explorer of Obsidian.

**Comment by kevboh** [comment]
You rarely if ever need to edit the index file directly. I sometimes keep project-level notes or themes in there, but in terms of its properties they're managed by the plugin. If you want to edit the frontmatter you'll need to toggle to source mode—we have no control over how preview renders it.
