### ISSUE TITLE
Bug: I cannot create a new scene note regardless of the file name.

### ISSUE THREAD

**Issue by kickTiger** [kevboh/longform#235]
## Versions
- Longform version: 2.0.6
- Obsidian version: 1.5.3
- OS: Windows 10 LTS 64-bit
- Theme: Default Obsidian Theme

## Describe the bug
I encountered a bug where I cannot create a new scene note regardless of the file name.

### Steps to reproduce the behavior:
1. Open Obsidian (version 1.5.3 with Longform 2.0.6).
2. Attempt to create a new scene note by providing a file name (e.g., "Test").
3. Receive an error message stating "A scene name cannot contain the characters."

## Expected behavior
I expected to be able to create a new scene note with the provided file name, whether it consisted of numbers or letters.

## Screenshots
![image](https://github.com/kevboh/longform/assets/3623068/e5dab39e-dd58-4f4e-bb74-81f57f9281c5)
![PixPin_2024-01-23_15-31-59](https://github.com/kevboh/longform/assets/3623068/e99d825a-bb7f-4836-a650-97fc1c89b99d)

## Additional context
After conducting several tests, I found that in version 1.5.3 with Longform 2.0.6, I received the same error message regardless of whether I input a file name consisting of pure numbers or pure letters. However, when I rolled back to version 2.0.5, I was able to create scene notes without any issues.

**Comment by kevboh** [comment]
Woof, thanks. Will fix today.

**Comment by kevboh** [comment]
This should be fixed in 2.0.7. Sorry about that—I don't have a Windows machine to test on.
