### ISSUE TITLE
Feature Request: use scene property instead of scene title during compile

### ISSUE THREAD

**Issue by ProductiveCoding** [kevboh/longform#237]
**Describe the solution you'd like**
Add a "scene_alias" field to the the front-matter of the note so that longform uses it instead of the scene title, when valorized. This allows the user to have a scene titled "chapter 1" but the scene-alias value in the compiled manuscript.md (i.e. "My first chapter") and even id for pandoc cross-references (i.e. "My first chapter {#sec:my_first_chapter}").
I implemented my solution adding the following piece of code after line 21306
            if (sceneInput.metadata.frontmatter.scene_alias != null)
            {
                title = title.replace("$1", sceneInput.metadata.frontmatter.scene_alias);
            }
            else
            {
                title = title.replace("$1", sceneInput.name);
            }

**Comment by b-camphart** [comment]
This could probably be done with a compile step, no?

**Comment by ProductiveCoding** [comment]
I don't know how toget the same result with a compile step

Il Gio 25 Gen 2024, 16:54 B. Camphart ***@***.***> ha scritto:

**Comment by kevboh** [comment]
A custom step, yes. Here's one, tested locally:

```js
module.exports = {
  description: {
    name: "Rename scenes to aliases",
    description: "Retitles scenes to their scene_alias property, if present",
    availableKinds: ["Scene"],
    options: [],
  },
  compile(scenes) {
    return scenes.map((scene) => {
      const fm = scene.metadata.frontmatter;
      if (!fm) {
        return scene;
      }
      return {
        ...scene,
        name: fm["scene_alias"] || scene.name,
      };
    });
  },
};
```

See [the docs](https://github.com/kevboh/longform/blob/main/docs/COMPILE.md#user-script-steps) on how to use it. You'll need to add this script as a `.js` file in your vault, then set the containing folder in Longform settings. After that the step will be available in the add compile step modal.

Remember to use this step _before_ stripping frontmatter (although it may still work, I just didn't go back and verify).

Closing, please lmk if you need more help using this feature.
