### ISSUE TITLE
Bug: Scenes continuing to disappear from project, index file loses the scene order, or the project does not reflect the index file

### ISSUE THREAD

**Issue by etobias-musiced** [kevboh/longform#238]
**Versions**
Longform version: 2.0.7
Obsidian version: 1.5.3
OS [e.g. macOS, Windows, iOS, Android]:  MacOS
Theme: Minimal
Other plugins that you think might be relevant here: Maybe Sync ?

**Describe the bug**
This is a continuation of issue #212 Forgetting All The Scenes, that was recently closed:

The index file keeps becoming empty or losing many of the files and the scenes are no longer recognized as being in a specific order or even being in the folder. This has happened at least 3 times in the past few days after some of the recent updates.
Screenrecording below

It's possible that something is happening with the project file syncing between computers? As I sometimes work on the project at home and at my job with two different computers.

**To Reproduce**
Open up Obsidian and access a project - and my longform project is no longer in order

**Expected behavior**
I expected the project file to be organized

**Screenshots**
[Screen recording here ](https://youtu.be/7-Odf3ySn-s)

**Additional context**
Attempted to edit the index file itself outside of Obsidian
Attempted to edit the index file in Obsidian
The files get added to the project again but are no longer in the order that is in the index file after I edit the index file directly.

I really appreciate this plugin when it is working!

**Comment by kevboh** [comment]
Let's use #212, which I've reopened.
