### ISSUE TITLE
Add option to `rename` scene to the context menu

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#24]
Similar to #16, only a rename option. The longform explorer is indeed more useful than the file explorer. But an option to rename scenes more easily is definitely missing.

**Comment by kevboh** [comment]
I'd considered this, but realized the editor itself allows renames. That said, I can add this feature--it does require a partial rewrite of the explorer, though.

**Comment by chrisgrieser** [comment]
yeah; i realized I could also use the header bar. It's not really a must-have-feature, but it would be nice to have, since using the editor instead of the context menu for renaming breaks with the usual habits.

**Comment by kevboh** [comment]
This will be in 2.0.

**Comment by p2edwards** [comment]
Hi @kevboh! Found a problem and a solution.

I noticed that renaming files from the Scene list **didn't automatically update links**. ("Updated X links in Y files"). 

**Simple fix**: in [SceneList](https://github.com/kevboh/longform/commit/07ef4935bd2dbac94e599862ac5d0838dc002428#diff-ee857e1eabc3eebe190f3da598b6d1bda41fc1d93316ae5d5c7b40428ba6ae17R198):
```diff
diff --git a/src/view/explorer/SceneList.svelte b/src/view/explorer/SceneList.svelte
index 4000ef8..3e7fdeb 100644
--- a/src/view/explorer/SceneList.svelte
+++ b/src/view/explorer/SceneList.svelte
@@ -195,7 +195,8 @@
         // Rename file
         const oldPath = scenePath(editingName, $selectedDraft, app.vault);
         const newPath = scenePath(newName, $selectedDraft, app.vault);
-        app.vault.adapter.rename(oldPath, newPath);
+        const file = app.vault.getAbstractFileByPath(oldPath);
+        app.fileManager.renameFile(file, newPath);
         editingName = null;
         return false;
       } else if (event.key === "Escape") {
```

This diff uses FileManager.renameFile - "Rename or move a file safely, and update all links to it depending on the user's preferences" ([ref](https://github.com/obsidianmd/obsidian-api/blob/3770989c2364ead5429eb7e4475e095588bbe914/obsidian.d.ts#L1122-L1127))

**Notes**

- FileSystemAdapter.rename(path, newPath) ([ref](https://github.com/obsidianmd/obsidian-api/blob/3770989c2364ead5429eb7e4475e095588bbe914/obsidian.d.ts#L1218-L1221)) is apparently just a thin-wrapper around OS file functions, and doesn't do the Obsidian link tracking magic. 
- Incidentally, there's also Vault.rename(file, newPath) ([ref](https://github.com/obsidianmd/obsidian-api/blob/3770989c2364ead5429eb7e4475e095588bbe914/obsidian.d.ts#L3482)), which also refrains from updating links. (I did try it just to see what it would do 😅 )

**Comment by wesleyboar** [comment]
The "Rename" option in the context menu of Scenes list is not effectual for me. Clicking it merely closes the context menu. And then I am unable to open the context menu in Scenes list, until I restart Obsidian.

Should I report this as a separate issue?

**Comment by kevboh** [comment]
I think using this one is fine—thanks for flagging.
