### ISSUE TITLE
Ctrl+Click Doesn’t bring up a new pane

### ISSUE THREAD

**Issue by Caddickbrown** [kevboh/longform#25]
This might be intentional in fairness, though functionality didn't work as expected

**Comment by kevboh** [comment]
ctrl+click on a scene, or something else? Thanks for the report!

**Comment by Caddickbrown** [comment]
On a scene yeah, you can get around it by opening a second pane and THEN going into Longform, but still not ideal

**Comment by kevboh** [comment]
This will be available in 2.0.
