### ISSUE TITLE
Corkboards in Longform

### ISSUE THREAD

**Issue by jsmm** [kevboh/longform#26]
Hi. It would be cool to have a corkboard for each Longform draft foder, as Scrivener does. This view shows each scene and its description in separate cards. This is already achievable in Obsidian with a Folder Note plugin.

With that plugin, however, scene cards are not sorted in the order manually chosen by the user in the Longform panel. 

This is a feature request, if you consider it of interest. Thanks for sharing this plugin.

**Comment by akadormouse** [comment]
I am experimenting with the kanban plugin for this.

**Comment by kevboh** [comment]
Yeah, it's a good idea. It's not a feature I ever used in Scrivener, so I didn't really prioritize it. But I'd like to have it.

**Comment by kevboh** [comment]
Tracking this in #148, which specifies using Canvas.

**Comment by nskeptic** [comment]
Corkboard/Story Grid/Plot Grid is an excellent idea, as long as it isn't implemented the way Scrivener does it. No way to link characters, and GUI subplots or scene breakdowns aren't possible in Scrivener. DabbleApp does this pretty well, allegedly LivingWriter does this too. They're never offline, though.

**Comment by b-camphart** [comment]
@nskeptic could you include a screenshot of what DabbleApp does that makes it different from Scrivener?  Their site doesn't have nearly any screenshots.

**Comment by nskeptic** [comment]
I was setting this up as a faction-by-faction plot board (horizontal) with Chapter/Scenes (vertical) but other things took priority back then. 

One could easily set up a different board and make it Event vs chapter or whatever. If you want to see what character/cast looks like I can share that tomorrow.

Does this help or should I elaborate?
![dabble plot tutorial](https://github.com/kevboh/longform/assets/147091760/f23de36f-1da0-48c4-aa4d-76c31ad0ec1f)
![dabble templates](https://github.com/kevboh/longform/assets/147091760/9eaa93e9-c074-49a3-8089-91dd31333d6c)
![dabble scene goal](https://github.com/kevboh/longform/assets/147091760/00d24cc0-5e51-4598-8cd9-98d99e3501dc)
![plot board](https://github.com/kevboh/longform/assets/147091760/394e8506-efa3-4a80-b974-880345c47d2d)
