### ISSUE TITLE
Feature Request: Expose scene order in properties

### ISSUE THREAD

**Issue by danipolani** [kevboh/longform#269]
**Describe the solution you'd like**
In order to integrate longform with other plugins like Projects or Dataview it will be nice to have scene order from longform plugin within scene files' properties. Currently to have the scenes ordered correctly in my dataview queries I have to manually add some value like `sceneOrder: 102030`, which is a duplication of data. And should I decide to reorder scenes in the longform view, I would have to update those values in every scene.

![image](https://github.com/user-attachments/assets/d34c9b40-6b8f-4532-b894-fb9346f3a6ac)

**Describe alternatives you've considered**
Alternatively, the scene order can be optionally prepended to the actual file name like in the longform view when scene numbers are on.

**Comment by kevboh** [comment]
You can do this now using the [api](https://github.com/kevboh/longform/blob/main/src/api/LongformAPI.ts) in a dataviewjs block.
