### ISSUE TITLE
README: "Linking Research": links in comments work

### ISSUE THREAD

**Issue by colintedford** [kevboh/longform#28]
In the README, section “Linking Research”, you say,

> In Obsidian, you can just…link to the note. Or put a comment next to the text. Maybe linking here requires special formatting to not render the link on preview—I’ll figure that out when I get to it 

You don’t have to do anything special — links in comments work in Edit Mode and are excluded from Preview mode. \o/

**Comment by kevboh** [comment]
Thanks
