### ISSUE TITLE
Scenes get re-ordered alphabetically when using the Git plugin to sync between devices

### ISSUE THREAD

**Issue by leethobbit** [kevboh/longform#29]
Hey there,

I use the Obsidian Git plugin to push my vaults to Github and then pull them for easy syncing and versioning.  I've noticed, however, that anytime I pull from Github it re-orders all of my Scenes into alphabetical order based on the name of Scene note.

Any tips for stopping this from happening?  Worst case scenario I know I can just name all of my scenes with numbers at the front, but that really reduces my ability to quickly shuffle them around so I thought I'd see if there was another way.

Thanks!

**Comment by kevboh** [comment]
This is fixed in the current 2.0 beta and will reach production in the near future; see https://github.com/kevboh/longform/issues/35 for details. Closing this issue as it’s tracked in the linked one.
