### ISSUE TITLE
Longform won't reset, doesn't create a project Index file

### ISSUE THREAD

**Issue by stoweboyd** [kevboh/longform#31]
I had Longform working, but today it ceased to work. I tried untracking all, I tried disabling, uninstalling, reinstalling. Nothing works.

**Comment by kevboh** [comment]
Weird! When you say "ceased to work," do you mean the pane itself doesn't appear? Are there any error messages in the console (View > Toggle Developer Tools)?

**Comment by kevboh** [comment]
@stoweboyd see above question!

**Comment by stoweboyd** [comment]
No, it appears. But when I 'mark as a Longform project' nothing happens. the Draft 1 isn't there when I switch to the Longform navigator. And when I right-click the test folder again the 'Mark as a Longform Project' shows again, not the Unmark option.

Is there some way to reset?

**Comment by kevboh** [comment]
@stoweboyd yes, there is, in the plugin settings. That will wipe all local project storage. Try that, but also keep an eye on the console (via developer tools), for errors, as it sounds like you may be hitting one—if so, any text that's displayed there would be very very useful.

**Comment by kevboh** [comment]
Closing, please reply if this was never resolved and I will reopen and try to help further.
