### ISSUE TITLE
Drafts get doubled at times

### ISSUE THREAD

**Issue by enteleos** [kevboh/longform#32]
Love the plugin! Starting my book in it, so hoping for good things after struggling, like you, with Scrivener, InDesign, etc.

Here's the problem I'm experiencing. From time to time, the index file doubles one of the Drafts folders, so it shows up twice in the Drafts list and the dropdown. I've attached a couple screen shots to show you what I mean, with "You" being the doubled Draft. As you can see, it shows as a single folder in the standard explorer view, but doubles inside the Longform view. The double is also located in the Index file as shown.

![image](https://user-images.githubusercontent.com/95007633/143373995-7f2cc1a6-002b-4e2a-884b-3dbd3562b5ad.png)

![image](https://user-images.githubusercontent.com/95007633/143373839-7d5cbc3e-86f4-4dd9-9f42-76ce3b3c30ed.png)

![image](https://user-images.githubusercontent.com/95007633/143374061-326f4471-ba60-45fd-a11d-9cb0cb97b5b5.png)

I am mystified about why it does this to some Draft folders, but not others. Occasionally it has also doubled a Draft without including all of the Scene files in each instance of the Draft inside the Index file. So far, I've solved this by deleting the duplicate listing in the Index file, with no apparent negative repercussions. I'm just getting started with my book, though, and don't have much content in there.

One possible factor: I am using Obsidian Sync. 

I'd be glad to help figure out what might be causing this. I'm not a coder, but will do what I can. What information would you like from me?

**Comment by kevboh** [comment]
Fascinating! This bug report is _super_ helpful. It looks like a race condition between files on disk and what Longform thinks are on disk. I can act on this with the info you've provided—thanks! And I think editing the index file directly to fix is fine for now as a band-aid.

**Comment by enteleos** [comment]
Awesome, glad to hear it. Good luck with this issue and with any other plans to build further on this awesome foundation. (I would definitely use the per-scene scratch notes, for example.)

**Comment by kevboh** [comment]
This is fixed in the current 2.0 beta and will reach production in the near future; see https://github.com/kevboh/longform/issues/35 for details. Closing this issue as it’s tracked in the linked one.
