### ISSUE TITLE
Total Word Count

### ISSUE THREAD

**Issue by stighagen** [kevboh/longform#33]
Hey. What a great plug-in! Love it. The only thing I'm missing is a total word count for the whole Draft. Would it be possible to create a small stat section, or maybe even better, individual word count in the list to the right of each scene, and then a total?

**Comment by kevboh** [comment]
This is fixed in the current 2.0 beta and will reach production in the near future; see https://github.com/kevboh/longform/issues/35 for details. Closing this issue as it’s tracked in the linked one.

**Comment by stighagen** [comment]
Wonderful! Thank you so much for supporting the community!
