### ISSUE TITLE
Confusion about process to add files

### ISSUE THREAD

**Issue by cashew90** [kevboh/longform#38]
Hi,

thank you for this very interesting plugin. There is one thing I really don't get: When marking a folder as longform, I expected to be able to choose from all the files the folder contains in Longform. However, that seems not to be the case. Why do I have to mark a folder as Longform in the first place, when I have to copy every file to the draft folder anyways? Thank you. :-)

**Comment by kevboh** [comment]
Hello!

So this will change with #35, but right now you mark a folder as such so that it can be available in the Longform panel. All marking a project does is tell Longform that it should be displayed there, and optionally create a few helper files—it doesn't move anything around or do anything to the files already in that folder.

How do you expect this to work? If you have a folder of files, what would you like to be the result? I'd love to handle your use case in #35.

**Comment by cashew90** [comment]
Hi,

I try to give a little insight in my thinking here: I write my PhD with Obsidian and have all my notes in there. Naturally, the project consists out of many different parts and I'd like to use Longform for this. The most important thing for me is that a tool won't add more complexity to my set-up than there currently already is. It already is verz complex because of well.. it's a PhD, after all. 😆 It is quite hard to keep track of different versions of parts, esp. when I try to incorporate feedback. My nightmare would be to have several vesions of a text (one in my folder, on in Longform), going back and forth not knowing what version is where. The way I expect it to work is something like this: I mark my PhD folder (containing all my notes related to my PhD project) as a Longform project and from this moment on I am able to choose in LF every note from this folder for arranging and compiling it. I'd like to have one canonical place for my text's versions and LF basically for three purposes (at this point): to differentiate it in terms of fonts (I love this feature), maybe to add a layer of meta information like writing status, versions, tags, etc, and to (re)arrange parts and compile/export them to a format of my choice (mostly PDF). 

Does this help? Thank you for your work!

**Comment by kevboh** [comment]
It does help! Where I'm lost is your concern around duplicating work. If you stick to a single draft, your thesis will exist in one folder. It will be the same as any other note in obsidian outside Longform. Is that your concern?

**Comment by cashew90** [comment]
I'm not sure whether I understand how the Scenes Feature works. This might be the issue. 😅 The way it would make the most sense to me would be: 1) Mark a folder as LF project, 2) Open Scenes, 3) Get a drop-down menu with all existing notes in the LF project folder, 4) (Re)Arrange them, mark them as 'in progress', 'done' etc, 5) compile it. My concern at the moment is that I already have a folder containing all the parts and if I want to work with them in LF I have to recreate them as scenes, don't I? Or do I misunderstand how the plugin works? Either way.. I find LF potentially extremely useful (also to contain LF projects, split them from the rest of my vault) but a little counter-intuitive.

**Comment by kevboh** [comment]
Okay, I think I see what's happening here. Scenes in Longform are just normal Obsidian notes. **Right now**, Longform requires these notes to be in a subfolder of a `Drafts` folder—changing that requirement is one aim of #35. You can customize the name of this `Drafts` folder, and using an empty string (`""`) will make it the root—I'm pretty sure I've seen someone get that working.

But to summarize, you don't need to duplicate scenes/notes as long as you're comfortable having them in a folder at Drafts/Draft 1 or similar. If you don't want that structure, you'll need to copy stuff around, unfortunately, until I implement #35.

**Comment by cashew90** [comment]
Ah, I see. Thank you for clarifying! Looking forward to #35. ☺️
