### ISSUE TITLE
Question about Folder hierarchies

### ISSUE THREAD

**Issue by ReaderGuy42** [kevboh/longform#39]
I really like your plugin! One issue I have with my workflow, is that I have to move my notes to the plugin's Draft folder to be able to have it compiled, which is my primary use of the plugin.

Would it be possible to have Longform recognize a single folder and just use all folders inside that folder, regardless of whether they are in subfolders?

Thanks :)

**Comment by kevboh** [comment]
I think this may be addressed by #35. Specifically, I want to give people more freedom in how a "project" is defined such that the Drafts folder is unnecessary.

Can you elaborate on how you use compile?

**Comment by ReaderGuy42** [comment]
Yeah, sure: I'm working on an academic paper with multiple chapters, and subchapters. On the Obsidian Forum someone suggested I just have the whole paper in a single note, with the option of linking between blocks/paragraphs, which would make the compiling unnecessary. However, since at this point my paper is already at the 10,000 word mark, I find this to be a bit unwieldy for a single note, since otherwise I could also just use Word or something like that; I like Obsidian since it allows me to quickly switch back and forth between notes that may just have a paragraph or a page or three.

However, with my workflow, (if that is what it is, not sure on the terminology?) I need to check every now and then how I'm progressing page/word-count wise, meaning that I'd have to either copy-paste everything into a single note, or use your compile function. (Transcluding, as of yet, is out of the running since I cannot get it to work right for me; it either just exports the note names in a .docx file, or it's a PDF with which I can then not work any further)

I love your compile function in concept. However with the Drafts/Draft1 folder hierarchy I'm still sort of locked into how I sort my notes. Whereas I'm using one folder for the introductory stuff, and then another folder for first chapter, etc. with a main note and then several other notes for appendices or whatever. If I then would like to use your compile function I then have to move all the notes into the Drafts/Draft1 folders, then sort them into the right order and then compile.

Hope this explains what I mean :) Thanks for your work!

**Comment by kevboh** [comment]
I see. It seems like what you'd like is the ability to treat a _folder hierarchy_ as a draft: in other words, any set of folders and/or markdown files should be viable as a single draft in Longform. Is that accurate?

Right now this isn't a thing you can do—Longform requires a single draft to be a flat folder of files. It's worth noting that #33 is tracking the word count issue, although I'd love for a different plugin to solve it...

More broadly, I'm not sure what a folder hierarchy as a draft would look like. I suppose it's one way to introduce #11.

**Comment by ReaderGuy42** [comment]
Yes, pretty much, you would set one folder as a Longform Project, as it is currently, but then it would treat all files in that folder and in subfolder (so recursively) as part of that project; optimally with the option of excluding specific notes. 

Generally, I'd even be happy with not having to use the double Drafts/Draft 1 folder hierarchy, but just simply having all the files in a folder count. However, since I have more than a dozen chapters and subchapters (and I'm not yet half way done), I have subfolders ot make it easier to navigate.

**Comment by kevboh** [comment]
Okay, that's helpful context. I'm going to close this ticket since it's been linked to the main sub-scene ticket above—we can continue discussion there as needed.
