### ISSUE TITLE
Feature Request: Sherlock the WordCount Dashboard

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#47]
Like, I already showed you the [WordCount Dashboard](https://gist.github.com/chrisgrieser/ac16a80cdd9e8e0e84606cc24e35ad99#file-word-count-dashboard-md) in earlier, but thinking about it, I think it makes sense for the Longform Plugin to sherlock that feature:
- total wordcount has been adressed a few times as a FR for the longform plugin already (e.g. #33)
- the dashboard is already primarily made for longform plugin users anyway
- the longform plugin would get a very useful feature that complements it
- sherlocking it would being able to integrate the dashboard and the longform plugin much better
- being a plugin, the Wordcount dashboard would get things like automatic updating
- it would make the setup of the dashboard much easier

I was actually thinking to make a separate plugin out of it, but I never really had the time to learn the things I would need to do that (code block processing, a settings menu, etc.). But I would not mind maintaining (and improving) the word-count-calculation part that already exists, if the wordcount dashboard would be sherlocked – it's basically only the knowledge of all the hooks and bridges to make a plugin out of it, that I lack.

**Comment by kevboh** [comment]
I'll look into it for sure. I have a few ideas around wordcount but if you've solved it I don't have to!

**Comment by kenanmike** [comment]
Seconded: found this request after searching for the same thing 🙌

**Comment by kevboh** [comment]
So I've been thinking about this a lot and am of two minds about fully integrating this. So far I have current scene/draft/project counts working locally, displaying in the Longform pane, but not an every-scene in an MS view. I plan on adding "sessions," so you can set count goals for a given day (or multiple sessions in the same day, set manually) and see how close you are to reaching them.

My concerns for integrating this are essentially:

- Plugins like [novel-word-count](https://github.com/isaaclyman/novel-word-count-obsidian) get close to (some of) it
- It makes a lot of assumptions about workflow: per-scene targets, scene statuses, etc.
- It's a lot of effort and my time is limited
- It could conflict or duplicate effort in the upcoming corkboard core plugin

It's really neat and impressive, and I think in the long term I'd love to have a holistic view of a project, especially with scene statuses, but I hesitate to add it _now_.

The other argument against it is, of course, that your solution exists for those who want it—and I suspect it is a bit of a power-user feature, in the end.

Does deferring this work in favor of simpler word count features and seeing what the corkboard does sound acceptable to you, @chrisgrieser?

**Comment by chrisgrieser** [comment]
Sure, of course!

I mean, I have a sunroom I am happy with, the main reason I opened the issue was that many other users also wanted such a feature, but easier to set up. I think for most ppl, displaying a count in the longform sidebar add you describe it is totally fine
