### ISSUE TITLE
option from note to add to longform project

### ISSUE THREAD

**Issue by hamishlow** [kevboh/longform#53]
Hi Kevin, It would be great if there was some kind of shortcut to add notes to a longform project from within the note, rather than having to return to the file explorer and dragging it in.... just a suggestion... thanks for the great work!

**Comment by kevboh** [comment]
@hamishlow You can create new notes (scenes) in the Longform panel by typing the note title into the New Scene field:

![image](https://user-images.githubusercontent.com/436032/153619762-e56befda-ab8e-4e59-ad00-42f005070629.png)
