### ISSUE TITLE
The panel cannot be clicked correctly

### ISSUE THREAD

**Issue by zhejiangwuyanzu** [kevboh/longform#54]
Thank you for your work，but  when I use longform, every time I click on those options, it will eventually become a move panel operation. I can't click them correctly
![image](https://user-images.githubusercontent.com/99970943/155277976-a1d148f4-7ab7-430e-9e6f-c34a99fe1dbb.png)

**Comment by kevboh** [comment]
This should be fixed in 2.0, after that release please reopen if you're still seeing this.
