### ISSUE TITLE
Longform plugin show generic 'plugin' title when using Minimal Themes vertical icons + name lay-out in sidebar

### ISSUE THREAD

**Issue by janpeeters70** [kevboh/longform#55]
Thanks for your great plugin.
I'm not sure if this is something that can be fixed in the Longform plugin or has to be added to Minimal Theme Settings plugin but when using Minimal Themes vertical icons + name lay-out the title is 'Plugin' instead of 'Longform'. 
Would be great if it would say longform. Thanks!

<img width="323" alt="20220314 Obsidian Longform" src="https://user-images.githubusercontent.com/4502360/158170161-bf50430b-ffa9-4d30-b2c5-17e4f4f088ef.png">

**Comment by kevboh** [comment]
Hmmm that's unusual, and not true for me using the default theme. I'll take a look at minimal to see what's going on.

**Comment by kevboh** [comment]
This will be fixed in version 2.0.
