### ISSUE TITLE
Bug? One specific file called "Appendix" isn't numbered in the sidebar overview

### ISSUE THREAD

**Issue by ReaderGuy42** [kevboh/longform#56]
I have a bunch of files (23) in my `Draft 1` folder and they all get numbered automatically, though I also use my own numbering scheme:

![image](https://user-images.githubusercontent.com/71895400/159027741-bfae9f53-b286-422c-8842-00ae3faa2133.png)

However, the file prefixed with 4.1.2 in this image does _not_ get a number by Longform. This is not a big deal at all; I just had to figure out why it was only showing me 22 files in this list; which is wrong, it does show all 23 files, but since the numbering ends at 22 here I was confused for a while.

The frontmatter in this file is not different than the others; I've changed the title, and that didn't change it.

Any ideas on that?
Thanks :)

EDIT: before even hitting submit I figured it out, though not how to solve it. The file name includes the word ´Appendix` which is throwing the plugin for a loop I guess because when I played around with the title it specifically doesn't number a file called "Appendix". I'm guessing that has something to do with a plugin file with that name?

Is this solvable?
Thanks :)

**Comment by kevboh** [comment]
I think this may be due to theming. Under the hood, scenes are listed as an HTML ordered list (`ol`) in the sidebar, but the numbers are removed. It seems that _something_ in your vault is causing the CSS that hides those numbers to show again.

What theme are you using? Any CSS snippets?

**Comment by ReaderGuy42** [comment]
You're right! I thought those numbers are there by default, but it seems the theme "Shimmering Focus" adds them there, thank you!! I'll ask over there :)
