### ISSUE TITLE
May be an error

### ISSUE THREAD

**Issue by windily-cloud** [kevboh/longform#58]
![image](https://user-images.githubusercontent.com/30640638/161971810-78805e99-baa0-464f-bcc3-f718ab27f810.png)

I didn't do anything, but the console reported an error. It doesn't affect the use, but isn't there something wrong with me somewhere?

Thanks for any reply!

**Comment by kevboh** [comment]
I'm not sure—this may not even be a longform error. Let me know if it affects the plugin and I'll reopen.
