### ISSUE TITLE
Bug: losing edits

### ISSUE THREAD

**Issue by pdworkman** [kevboh/longform#60]
I haven't managed to figure out how to replicate this yet, but I have seen this happen a few times the last couple of days. 

I edit a Longform scene in Obsidian, then copy and paste it into Grammarly, and it is the unedited version. Go back to Obsidian, and it has reverted to the previous version. Very irritating. 

I tried using version history to see it I can go back and grab the edited version, but version history is blank.

I think that it might be a conflict with Breadcrumbs plugin, as I cleverly decided to use Next in the metadata to allow me to Next/Previous navigate through scenes. The first thing I have been changing when I start my editing on a scene is to add the Next: [[scene name]] into the metadata. When I copy and paste the scene into Grammarly, the Next: line is missing, and so are the rest of my edits. Or at least some of them. 

I will keep watching and try to give you replicatable steps. 

When does Longform save a scene? Anything unusual going on there?

**Comment by pdworkman** [comment]
I forgot that I was using Dropbox to sync this archive, not Obsidian sync. So that's why the versions is empty.

I suspect that this may be a conflict between Breadcrumbs and Dropbox rather than anything to do with Longform but am still trying to figure it out. Leaving this up in case anyone else experiences the same issue.

**Comment by pdworkman** [comment]
Turned off Breadcrumbs and it stopped the data loss. But I haven't experienced this same data loss in my other vault where I have Breadcrumbs installed but not Longform. So I still think it is a conflict between the two.

**Comment by kevboh** [comment]
Longform doesn't touch the contents of scene files at all—it never reads or writes them. Sorry to hear you lost some work from some other cause, though…never feels good.
