### ISSUE TITLE
Mobile UX Scroll Issues

### ISSUE THREAD

**Issue by PeteMichaud** [kevboh/longform#62]
Hey man! I’ve been really enjoying your plugin, thanks a lot for writing it. Looking forward to the new version too :)

Half my work is done on my ipad so mobile usability is very important.There is a usability issue on mobile though: when I open the side menu and see my scenes, I naturally try to drag the menu up and down to see the contents. In the current form this immediately grabs whatever scene is under my finger and moves it around, dropping it where I let go. To actually scroll I have to make sure my finger is directly on top of the thin, right edge of the menu. 

So here are a few suggested changes:

1. One aspect that makes the surprise scene reordering particularly annoying is that it can’t be undone, so I can just have to figure out manually where that scene used to be. Implement undo on scene reordering.
2. The normal drag event on the whole menu should be for scrolling only
3. The reordering scenes should require a touch and hold event, which selects the item for dragging
4. Short Tapping should open the scene as it does now

—

By the way, if you want any help with the new version, please let me know I may be able to take some of the workload if I know what PRs you’re interested in.

**Comment by kevboh** [comment]
I'll take a look at these. I use [SortableJS](https://github.com/SortableJS/Sortable) for scene reordering, so it will come down to what it supports.

Undo is interesting, I'll have to see if I can intercept the right keystrokes + focus combination.

**Comment by kevboh** [comment]
Oh wow yeah this is pretty bad! I'll dig into this over the next few days.

**Comment by kevboh** [comment]
The good news (I guess) is that the next version has commands that mean you never have to touch the scenes tab, really. But still!

**Comment by kevboh** [comment]
The next version will:

- delay drag and drop on mobile to allow normal scrolling
- include undo/redo support for reordering
