### ISSUE TITLE
Flat file hierarchy?

### ISSUE THREAD

**Issue by codeluggage** [kevboh/longform#64]
Can Longform be used if obsidian is used without folders? 

I.e. if a Dendron style hierarchy of notes is used instead of folders, could Longform match on filename prefixes instead of folders?

**Comment by kevboh** [comment]
Not _yet_. I'm working on refactoring project management such that you can store stuff all in one folder (root, in your case). Would not be based on filename prefixes.

**Comment by codeluggage** [comment]
Cool! Looking forward to seeing if I can make it work well with hierarchical notes 👍

**Comment by kevboh** [comment]
Is requiring a folder that isn't foot a deal-breaker for you? You use no folders at all?

**Comment by codeluggage** [comment]
Yes, it would be for everyone using Dendron and Obsidian together. 

Or rather, it breaks if there's no way to configure the target folder through a setting. When it is configurable, the root can be set as the target, which tends to fix everything.

**Comment by kevboh** [comment]
I'm not familiar with Dendron. I'd like to be able to support what you want to do, but not at the expense of how it best works in Obsidian over other tools.
