### ISSUE TITLE
QoL Feature Request: "Next/Previous Scene" Command

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#65]
Just a minor feature to add, but two commands for "next/previous scene" would be nice, to navigate a longform project with the keyboard

**Comment by kevboh** [comment]
Great idea, thanks.

**Comment by chrisgrieser** [comment]
Recently, there has been a new plugin that does something similar, but based on the file explorer: https://github.com/kzhovn/file-explorer-keyboard-nav

maybe some part of the code can be used for this feature?

**Comment by chrisgrieser** [comment]
okay, this was actually not too hard to code myself as a templater script. I do am missing one or to pieces to integrate this properly in the longform plugin, but otherwise, you can also simply copypaste this:


```js
<%*
// CONFIG
const forwards = false;
//----------------------------

const curFile = this.app.workspace.getActiveFile();
const draft = curFile.parent.name;
// TODO: there should probably be a cleaner way of getting the path, using longform plugin data
const indexPath = curFile.parent.parent.parent.path + "/Index.md";

// get Longform Drafts Order from index
const indexFile = this.app.vault.getAbstractFileByPath(indexPath);
const draftOrder = this.app.metadataCache.getFileCache(indexFile)
  .frontmatter
  .drafts
  .filter(d => d.name === draft)[0]
  .scenes;

// open next file
let nextFileIndex;
if (forwards) {
  nextFileIndex = draftOrder.indexOf(curFile.basename) + 1;
  if (nextFileIndex === draftOrder.length) nextFileIndex = 0;
} else {
  nextFileIndex = draftOrder.indexOf(curFile.basename) - 1;
  if (nextFileIndex === -1) nextFileIndex = draftOrder.length - 1;
}

const nextFile = draftOrder[nextFileIndex];
const nextFilePath = curFile.parent.path + "/" + nextFile + ".md";
const nextTFile = this.app.vault.getAbstractFileByPath(nextFilePath);
await this.app.workspace.activeLeaf.openFile(nextTFile);

// This makes sure Templater doesnt replace any text that was selected
return;
%>
```

**Comment by kevboh** [comment]
Yeah this is pretty much what I would do. Amazing! I'll look at incorporating this when I finally have time to work on Longform again, my life has been kind of wild for the past couple of months but is finally easing up a bit.

**Comment by kevboh** [comment]
Just to follow up here, I'm planning on adding a bunch of navigation commands to Longform, including:

- Previous Scene
- Next Scene
- Indent Scene
- Unindent Scene
- Next Scene at this Indentation Level
- Previous Scene at this Indentation Level

**Comment by chrisgrieser** [comment]
tested in the beta and works fine 🙂
