### ISSUE TITLE
Feature Request: Allow root folder for scenes in Pane

### ISSUE THREAD

**Issue by chrismelbourne** [kevboh/longform#67]
Assume the Longform folder is "MyLongform", which has a subfolder called "Drafts" which has another subfolder called, say, "Whatever"

Currently the Longform Pane allows the user to choose:

MyLongform > Whatever  as the default scene, but not MyLongform folder itself.

Would be super-helpful if somehow all the pages in MyLongform can be the scenes. That's helpful for a single project without having to bother with subfolders nested twice (> Draft > Whatever).

Thanks.

**Comment by kevboh** [comment]
Just to clarify: you're asking for a project structure like

```
MyProject/
    |---- Scene 1.md
    |---- Scene 2.md
...
```

and not for all scenes to be in the root of your vault, correct? If so, that is an aim of #35. If not, and you want a project & its scenes to all be able to live in the root of your vault, it's slightly out of scope of the plugin at present.

**Comment by chrismelbourne** [comment]
Yes, exactly, the scenes would live in the root of the project (and not the vault). Glad to hear it's already on the roadmap! Thanks!

**Comment by kevboh** [comment]
You can also do this right now by entering “/“ as the drafts path when creating a new project.

**Comment by chrismelbourne** [comment]
Not sure I understand, I can't find a "drafts" path in settings. Also, I've already got all my scenes under "My project" instead of "My project/drafts/draft 1" and I'm hesitant to move them as Git history will break.

**Comment by kevboh** [comment]
Sure. Another way to say this is: you can do this right now by setting the `drafts.folder` frontmatter to `/` in the Index file.

**Comment by chrismelbourne** [comment]
> Sure. Another way to say this is: you can do this right now by setting the `drafts.folder` frontmatter to `/` in the Index file.

I'ved edited the index.md file as follow (adding the folder / to the list):
---
version: 1
workflow: Default Workflow
drafts:
  - name: drafts1
    folder: drafts1
    scenes:
  - name: current
     folder: /
     scenes:
---

But every time I force reload or restart Obsidian, the folder "/" disappears from the frontmatter and also from the Longform tab as an option. Any ideas?
