### ISSUE TITLE
[UI] Text boxes out of bounds

### ISSUE THREAD

**Issue by FongTsang** [kevboh/longform#72]
Dear Kevboh, I noticed that some boxes in compile panel is out of the bounds, hope this can be fixed. thanks a lot.
![图片](https://user-images.githubusercontent.com/53118840/175758349-744435cc-ebf5-4776-a816-09bd89fd2d30.png)

**Comment by kevboh** [comment]
Thanks, I'll take a look.

**Comment by kevboh** [comment]
This will be fixed in #35
