### ISSUE TITLE
Add support for parts

### ISSUE THREAD

**Issue by radioactive-penguin** [kevboh/longform#76]
I'm slowly converting my writing over to Obsidian/Longform from Scrivener.  One thing that I've noticed is that there is no support for parts.  I think this could be worked out with a folder for the scene to go into. for now, I'm just creating a blank scene with the part title and will manually change the header on those in the compiled draft.

Just a thought.

**Comment by kevboh** [comment]
This feature is in the current beta! See #11 and #35 for details. It works a little differently from how you describe it here: notes can be the parents of other notes. I'm thinking about how to integrate folders into this setup, but it won't be part of 2.0.
