### ISSUE TITLE
Bug: Custom Compile Step of kind `Scene` has no content

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#77]
I tried to created a custom compile step that runs on Scenes, however, multiple problems occurred that do not occur with when I run the very same step on the Manuscript. Here is a minimal custom compile step with which I could reproduce the issue:
```js
module.exports = {
  description: {
  	name: "Sample Script",
  	description: "Replaces every 'a' with an explosion emoji.",
  	availableKinds: ["Scene", "Manuscript"],
  	options: []
  },
  compile (input, context) {
  	input.contents = input.contents.replaceAll ("a", "💥");
  	return input;
  }
};
```

Running this leads to an error with the following console message:
```log
plugin:longform:3069 [Longform] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at Object.compile (eval at <anonymous> (plugin:longform:1:1), <anonymous>:15:35)
    at eval (plugin:longform:3066:43)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:longform:28:58)
```

it seems that for whatever reason, the `input.content` is undefined. At first I thought this was maybe due to scenes with no content or something, and added `if (!input.contents) return input;` as guard clause:
```s
compile (input, context) {
  	if (!input.contents) return input;
  	input.contents = input.contents.replaceAll ("a", "💥");
  	return input;
  }
```
however, now the custom step does not seem to run at all, implicating that for whatever reason, all scenes are missing `input.contents`?

(used Longform version 1.1 for this)

**Comment by kevboh** [comment]
Oh wow, the compile docs have a pretty bad typo in them: scene (and join) steps are passed an array as `input` of the type listed in the docs, not the flat type. In other words, `compile()` is called once _on an array of all scenes_, which is why your step is failing. Here's how to fix it:

```
module.exports = {
  description: {
  	name: "Sample Script",
  	description: "Replaces every 'a' with an explosion emoji.",
  	availableKinds: ["Scene", "Manuscript"],
  	options: []
  },
  compile (input, context) {
        // omitted: check `context` for type of step, which will determine shape of `input`
  	return input.map(i => {
            const contents = i.contents.replaceAll ("a", "💥");
            return { ...i, contents };
        });
  }
};
```

n.b. the comment about omitted code.

[Here](https://github.com/kevboh/longform/blob/main/src/compile/steps/strip-frontmatter.ts) is an example of this kind of step.

I'll fix the docs.

**Comment by chrisgrieser** [comment]
ah, now I see. Thanks!
