### ISSUE TITLE
Allow for Sharing of Custom Compile Steps

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#78]
I have by now created a bunch of Custom Compile steps (among others: #44, #48), and I was wondering whether you could maybe designate a place collecting custom user steps? I assume my custom steps could also be of interest to others.

For example a folder in the repo, to which one can make PRs? The contents of that folder could then be displayed in the compile step collection, but under a heading "Community Steps", that way people without coding skills can access them, but it is clear that you are not responsible for fixing bugs with them like with the built-in steps (which could lighten the workload for you).

Also, this would have the added benefits of providing some examples for others, which you could refer to in the [compile docs](https://github.com/kevboh/longform/blob/main/docs/COMPILE.md).

**Comment by kevboh** [comment]
Ha, I was just thinking about exactly this a couple of days ago. I want to do it; there are definitely security concerns, but I think having them be PRs against some folder here could solve for that. Thanks for clarifying it!

**Comment by b-camphart** [comment]
@kevboh What about having a project here in github as a list of custom compile steps?  Users would need to understand that they download and use them at their own risk, but it could provide a way to have a repository of steps without cluttering the issues list.

**Comment by kevboh** [comment]
@b-camphart yeah, I think that's a reasonable solution—I assume by project in github you mean a dedicated repo?

**Comment by b-camphart** [comment]
I was actually thinking of creating a project within this repo as a way of keeping it closely related, but it turns out that github projects can't be publically writable.  So, yeah, maybe a separate repository.

**Comment by kevboh** [comment]
Yeah, I think dedicated repo with PRs is best.

**Comment by kevboh** [comment]
This now lives at https://github.com/obsidian-community/longform-compile-steps. Thanks @chrisgrieser!
