### ISSUE TITLE
Drafts: Last selected draft not reliably remembered

### ISSUE THREAD

**Issue by Moonbase59** [kevboh/longform#8]
The currently selected draft is somehow not persistent. In my 3-drafts test (from the 200k word test), when I select "Draft 3" (the latest), Longform drops back to "Draft 2" after reopening Obsidian.

This can lead to dramatic errors if a writer doesn’t realize (s)he is working in the wrong draft.

Let me know what info you need to fix this.

![Auswahl_179](https://user-images.githubusercontent.com/3706922/128633122-8b273498-b03e-4d3d-8a4d-597eb401d229.png)

![Auswahl_180](https://user-images.githubusercontent.com/3706922/128633126-7fc2d64b-48ad-4779-a850-00e738bcc879.png)

**Comment by kevboh** [comment]
Updating title to clarify it's the _setting_ that's not always persisting (I can't reproduce this currently), not the folders and notes themselves.

**Comment by Moonbase59** [comment]
First tests with 1.0.3 seem to show this has been fixed.

**Comment by kevboh** [comment]
I'll close for now, and we can reopen if it recurs.
