### ISSUE TITLE
Beta: Various Index file problems

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#81]
[The docs for the index file](https://github.com/kevboh/longform/blob/main/docs/INDEX_FILE.md#the-longform-entry) are either outdated or the plugin's behavior does not reflect them yet.
- `version` is a required key according to the docs, yet it is not added in the frontmatter after migration/using the `Insert frontmatter` command. So it isn't required?
- `sceneFolder` seems to be only `folder` now?
- `string[]` is a technical signifier, non-coders are not familiar with what that means.
- considering that the last version of longform repeatedly stated that the index file should not be edited, you should mention in the docs that for version 2.0, the index file can be edited (and you are even encouraged to do so to use now, to be able to use some new features!)

General issues with the index file:
- having keys which one should *not* edit, while having other keys, which one *should* edit will lead to quite a lot of confusion. 
- ➡️ I suggest removing the `version` and `workflow` key, and save the respective information in the plugin's `data.json`.
- ➡️ for the `format` key, I suggest to use a simple `longform-single-scene` yaml key instead of `longform` for those scenes, and omit the key in multi-scene-projects.

**Comment by kevboh** [comment]
The docs are out of date.

As for the issues you've listed:

- `version` was removed a while ago, just still in the docs
- I want to keep `workflow` in the index file, but you should never need to edit it directly. In fact, you should never have to edit any YAML directly, it's just there for you if you'd like to. What feature were you thinking of that requires editing YAML?
- The `format` requirement is a kind of soft-check on performance. By requiring a parent and child key, I prevent issues where people have `longform` at frontmatter root for non-Longform projects. Not a huge deal either way, but I like the consistency of a standard structure.

**Comment by chrisgrieser** [comment]
> In fact, you should never have to edit any YAML directly, it's just there for you if you'd like to. What feature were you thinking of that requires editing YAML?

- There is no method for setting a `title`, other than with yaml, or am I missing something?
- same for the folder?

**Comment by kevboh** [comment]
You can set title in the Project tab.

True, there's no way to set folder outside of YAML. It's sort of a hidden feature, but I suppose I can expose it in the Project tab as well...
