### ISSUE TITLE
Bug (Beta): changing the `folder` in a longform multi-scene-index-note does not work

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#82]
When the `folder` key is kept with the value `/`, everything seems to work fine. However, changing/trying to change the value leads to multiple issues:
1. The value reverts back to `/` as soon as I add a file to the intended scene folder. It also reverts back when I select `add` or `ignore` via the unknown file wizard.
2. Any value change is actually not recognized, i.e. even during the time the value has not reverted back, creating/moving a file into that folder does not trigger the "unknown file" detection (but rather reverts the value to `/`, as described in 1)
3. Adding a new scene via `New Scene...` does add the scene correctly into the `scene` yaml, but does not respect the value set in `folder`.

**Comment by kevboh** [comment]
Wow, so this was a typo: when I ingest index data I look for a key named `sceneFolder`, but when I write it back out I use the key `folder`. I _intended_ for it to be `sceneFolder`, so I'll correct output to be that (it's also `sceneFolder` in the docs).
