### ISSUE TITLE
Docs: Add info on how `- - - key` works in YAML

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#83]
I am having a hard time figuring out how to make dataview read correctly those multi-indention yaml-keys. Given the example from the docs:

```yaml
scenes:
    - - - first
      - second
    - third
    - - - - - - - fourth
```

I can get the third one via `scene.third`, but how do I access the others? Is that `scenes[0][0][0]` for the first one? 🥴  And is it `scenes[0].second` for the second? 🙈

**Comment by chrisgrieser** [comment]
Also, how exactly does all that translate to `indentationLevel ` when writing a custom compile step?

**Comment by chrisgrieser** [comment]
So from what I can tell, the longform plugin somehow parses the `scenes[0][0][0]` stuff into indention levels. is there some "how deep does this object go" method in javascript? Or how exactly does the longform plugin parse the indention level of the elements in the `scene` array? 🤔 

Like, even If I wrote a function myself, for consistency, it would be important to actually use the same method as the longform plugin 🤔

**Comment by kevboh** [comment]
So there's an API now that ships a function to do this translation: https://github.com/kevboh/longform/blob/main/src/api/LongformAPI.ts#L44-L76

As you can see, the API itself is documented, but there aren't corresponding markdown docs. I think that's okay?

As for how this works: these are arbitrarily-nested arrays, which means that example corresponds to:

```
[
 [ [ 'first' ] ],
  'second',
  [ 'third' ],
  [ [ [ [ [ [ 'fourth' ] ] ] ] ] ] 
]
```

Obviously this is nonsense. BUT we can recurse through the array to figure out the depth of each element, and annotate it with its indentation level—that's what that API function does. There's also an API function to go the other direction.

Longform runs these functions when it reads and writes the YAML, and it stores the one-dimensional, annotated version in memory. It then uses this for all UI and compile, which is how `indentationLevel` ends up in compile steps.

Does that help?

**Comment by chrisgrieser** [comment]
> As you can see, the API itself is documented, but there aren't corresponding markdown docs. I think that's okay?

well, I think what's written there is fine. Maybe add that link to the API somewhere in the longform docs, so people can be aware of it

---

Otherwise, just for reference, I cannot actually test how well this API works since getting the `scenes` array does not work due to another problem (#87)
