### ISSUE TITLE
FR: Numbering of Scenes in the sidebar

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#84]
Now that we have indentation levels and sub-scenes, the simple CSS solution of numbering all scenes does not work anymore. Now, to get proper numbering (e.g. `1.3.4`), that would have to be done on the plugin's side.

**Comment by kevboh** [comment]
Makes sense. I might go even further: a setting to do automatic numbering, and those numbers can be overridden by scene frontmatter, something like

```
sceneNumber: 3.2
```

and maybe also

```
restartNumbering: true
```

to tell Longform to use the custom number as the base number going forward. I will often begin my longer things with scenes for epigraphs, forewords, etc., so a way to incorporate those without throwing off numbering seems useful. If it's too much I'll just do the simple numbering for 2.0 and the frontmatter in a later release.

**Comment by chrisgrieser** [comment]
Since you rarely have two enumrations in a project, I think something like a yaml to ignore a scene for the numbering (e.g. for a prolog or abstract) might be the most straightforward solution? 

For Compatibility, you could also consider using `{-}` in the filename, [as Pandoc does](https://pandoc.org/MANUAL.html#heading-identifiers)?

**Comment by kevboh** [comment]
This will be available (behind a setting that defaults to off) in the next beta. I’ve also updated the `Prepend Title` compile step to use these proper numbers for its `$2` token.
