### ISSUE TITLE
FR: Quick Switcher for current Longform Project

### ISSUE THREAD

**Issue by chrisgrieser** [kevboh/longform#85]
A Quick Switcher that *exclusively* works on scenes of the current note (indicating things like indentation level, parent scene etc.) could be very useful to navigate large longform projects.

Not an important feature, but a very useful one for down the road maybe?

**Comment by kevboh** [comment]
This will be available in the next beta. Your suggestion of indicating indentation level was good: the jump modal by default shows all scenes in order and indented (ignore scene names here, they were moved around and no longer make sense):

<img width="707" alt="image" src="https://user-images.githubusercontent.com/436032/183319137-7739aa31-d0f8-4a8e-ad6b-b912f27bfa8d.png">
