### ISSUE TITLE
Word counter stops counting on paste

### ISSUE THREAD

**Issue by GamerGirlandCo** [kevboh/longform#93]
i need to reload the app to get it to work again. this means i have to type any text i cut word by word.

**Comment by pdworkman** [comment]
Finished yesterday's session at 5046 words. Today I apparently only wrote 98 more to get to 10,101.

![image](https://user-images.githubusercontent.com/91858203/210479575-773cbb91-0dd2-4fd4-ac17-12d6e236d40d.png)

**Comment by kevboh** [comment]
Looks like it's double-counting. I'll have to take a look. Hard to repro this sort of thing without data, unfortunately.
