### ISSUE TITLE
issue in compiling an embedded callout note

### ISSUE THREAD

**Issue by olivered-alt** [kevboh/longform#95]
Hi, 
The [[ ]]] are missing when I compile an embedded callout note such as 
> [!quote] 
> ![[^^ quotation]]
Instead I get 
!^^ quotation without [[ ]]
Thanks!

**Comment by olivered-alt** [comment]
Hi! If the "remove links" button is turned off, the manuscript view in Obsidian shows the text of the "embed link" correctly. Unfortunately the related .md file in the finder shows the link ![[REF^XXX]]. For the time being I make a pdf export on the manuscript file in obsidian and then convert it into word. 
Thanks for your follow-up!

**Comment by b-camphart** [comment]
@kevboh I think this one should have been closed with #194
